/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AzFramework Public Precompiled Header
// Contains ALL public AzFramework headers. Applied as a PUBLIC PCH so that
// all targets depending on AzFramework automatically benefit from precompiled headers.
// AzCore's public PCH is inherited through the build dependency chain.
// Controlled by the LY_PCH CMake option (default: ON).

#pragma once
#include <AzFramework/API/ApplicationAPI.h>
#include <AzFramework/Application/Application.h>
#include <AzFramework/Archive/Archive.h>
#include <AzFramework/Archive/ArchiveBus.h>
#include <AzFramework/Archive/ArchiveFileIO.h>
#include <AzFramework/Archive/ArchiveFindData.h>
#include <AzFramework/Archive/ArchiveVars.h>
#include <AzFramework/Archive/Codec.h>
#include <AzFramework/Archive/IArchive.h>
#include <AzFramework/Archive/INestedArchive.h>
#include <AzFramework/Archive/MissingFileReport.h>
#include <AzFramework/Archive/NestedArchive.h>
#include <AzFramework/Archive/ZipDirCache.h>
#include <AzFramework/Archive/ZipDirCacheFactory.h>
#include <AzFramework/Archive/ZipDirFind.h>
#include <AzFramework/Archive/ZipDirList.h>
#include <AzFramework/Archive/ZipDirStructures.h>
#include <AzFramework/Archive/ZipDirTree.h>
#include <AzFramework/Archive/ZipFileFormat.h>
#include <AzFramework/Asset/AssetBundleManifest.h>
#include <AzFramework/Asset/AssetCatalog.h>
#include <AzFramework/Asset/AssetCatalogBus.h>
#include <AzFramework/Asset/AssetCatalogComponent.h>
#include <AzFramework/Asset/AssetProcessorMessages.h>
#include <AzFramework/Asset/AssetRegistry.h>
#include <AzFramework/Asset/AssetSeedList.h>
#include <AzFramework/Asset/AssetSystemBus.h>
#include <AzFramework/Asset/AssetSystemComponent.h>
#include <AzFramework/Asset/AssetSystemTypes.h>
#include <AzFramework/Asset/Benchmark/BenchmarkAsset.h>
#include <AzFramework/Asset/Benchmark/BenchmarkCommands.h>
#include <AzFramework/Asset/Benchmark/BenchmarkSettingsAsset.h>
#include <AzFramework/Asset/CustomAssetTypeComponent.h>
#include <AzFramework/Asset/FileTagAsset.h>
#include <AzFramework/Asset/GenericAssetHandler.h>
#include <AzFramework/Asset/SimpleAsset.h>
#include <AzFramework/Asset/XmlSchemaAsset.h>
#include <AzFramework/AzFrameworkAPI.h>
#include <AzFramework/AzFrameworkModule.h>
#include <AzFramework/CommandLine/CommandLine.h>
#include <AzFramework/CommandLine/CommandRegistrationBus.h>
#include <AzFramework/Components/AzFrameworkConfigurationSystemComponent.h>
#include <AzFramework/Components/CameraBus.h>
#include <AzFramework/Components/ComponentAdapter.h>
#include <AzFramework/Components/ComponentAdapterHelpers.h>
#include <AzFramework/Components/ConsoleBus.h>
#include <AzFramework/Components/DeprecatedComponentsBus.h>
#include <AzFramework/Components/EditorEntityEvents.h>
#include <AzFramework/Components/NonUniformScaleComponent.h>
#include <AzFramework/Components/TransformComponent.h>
#include <AzFramework/Device/DeviceAttributeDeviceModel.h>
#include <AzFramework/Device/DeviceAttributeGPUModel.h>
#include <AzFramework/Device/DeviceAttributeInterface.h>
#include <AzFramework/Device/DeviceAttributeRAM.h>
#include <AzFramework/Device/DeviceAttributesSystemComponent.h>
#include <AzFramework/DocumentPropertyEditor/AdapterBuilder.h>
#include <AzFramework/DocumentPropertyEditor/AggregateAdapter.h>
#include <AzFramework/DocumentPropertyEditor/BasicAdapter.h>
#include <AzFramework/DocumentPropertyEditor/CvarAdapter.h>
#include <AzFramework/DocumentPropertyEditor/DocumentAdapter.h>
#include <AzFramework/DocumentPropertyEditor/DocumentSchema.h>
#include <AzFramework/DocumentPropertyEditor/ExpanderSettings.h>
#include <AzFramework/DocumentPropertyEditor/FilterAdapter.h>
#include <AzFramework/DocumentPropertyEditor/MetaAdapter.h>
#include <AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h>
#include <AzFramework/DocumentPropertyEditor/PropertyEditorSystem.h>
#include <AzFramework/DocumentPropertyEditor/PropertyEditorSystemInterface.h>
#include <AzFramework/DocumentPropertyEditor/Reflection/Attribute.h>
#include <AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.h>
#include <AzFramework/DocumentPropertyEditor/Reflection/Visitor.h>
#include <AzFramework/DocumentPropertyEditor/ReflectionAdapter.h>
#include <AzFramework/DocumentPropertyEditor/RoutingAdapter.h>
#include <AzFramework/DocumentPropertyEditor/SettingsRegistrar.h>
#include <AzFramework/DocumentPropertyEditor/SettingsRegistryAdapter.h>
#include <AzFramework/DocumentPropertyEditor/SortAdapter.h>
#include <AzFramework/DocumentPropertyEditor/ValueStringSort.h>
#include <AzFramework/Entity/BehaviorEntity.h>
#include <AzFramework/Entity/EntityContext.h>
#include <AzFramework/Entity/EntityContextBus.h>
#include <AzFramework/Entity/EntityDebugDisplayBus.h>
#include <AzFramework/Entity/EntityOwnershipService.h>
#include <AzFramework/Entity/EntityOwnershipServiceBus.h>
#include <AzFramework/Entity/GameEntityContextBus.h>
#include <AzFramework/Entity/GameEntityContextComponent.h>
#include <AzFramework/Entity/PrefabEntityOwnershipService.h>
#include <AzFramework/Entity/SliceEntityOwnershipService.h>
#include <AzFramework/Entity/SliceEntityOwnershipServiceBus.h>
#include <AzFramework/Entity/SliceGameEntityOwnershipService.h>
#include <AzFramework/Entity/SliceGameEntityOwnershipServiceBus.h>
#include <AzFramework/FileFunc/FileFunc.h>
#include <AzFramework/FileTag/FileTag.h>
#include <AzFramework/FileTag/FileTagBus.h>
#include <AzFramework/FileTag/FileTagComponent.h>
#include <AzFramework/Font/FontInterface.h>
#include <AzFramework/Gem/GemInfo.h>
#include <AzFramework/InGameUI/UiFrameworkBus.h>
#include <AzFramework/Input/Buses/Notifications/InputChannelNotificationBus.h>
#include <AzFramework/Input/Buses/Notifications/InputDeviceNotificationBus.h>
#include <AzFramework/Input/Buses/Notifications/InputSystemNotificationBus.h>
#include <AzFramework/Input/Buses/Notifications/InputTextNotificationBus.h>
#include <AzFramework/Input/Buses/Requests/InputChannelRequestBus.h>
#include <AzFramework/Input/Buses/Requests/InputDeviceRequestBus.h>
#include <AzFramework/Input/Buses/Requests/InputHapticFeedbackRequestBus.h>
#include <AzFramework/Input/Buses/Requests/InputLightBarRequestBus.h>
#include <AzFramework/Input/Buses/Requests/InputMotionSensorRequestBus.h>
#include <AzFramework/Input/Buses/Requests/InputSystemCursorRequestBus.h>
#include <AzFramework/Input/Buses/Requests/InputSystemRequestBus.h>
#include <AzFramework/Input/Buses/Requests/InputTextEntryRequestBus.h>
#include <AzFramework/Input/Channels/InputChannel.h>
#include <AzFramework/Input/Channels/InputChannelAnalog.h>
#include <AzFramework/Input/Channels/InputChannelAnalogWithPosition2D.h>
#include <AzFramework/Input/Channels/InputChannelAxis1D.h>
#include <AzFramework/Input/Channels/InputChannelAxis2D.h>
#include <AzFramework/Input/Channels/InputChannelAxis3D.h>
#include <AzFramework/Input/Channels/InputChannelDelta.h>
#include <AzFramework/Input/Channels/InputChannelDeltaWithSharedPosition2D.h>
#include <AzFramework/Input/Channels/InputChannelDigital.h>
#include <AzFramework/Input/Channels/InputChannelDigitalWithPosition2D.h>
#include <AzFramework/Input/Channels/InputChannelDigitalWithSharedModifierKeyStates.h>
#include <AzFramework/Input/Channels/InputChannelDigitalWithSharedPosition2D.h>
#include <AzFramework/Input/Channels/InputChannelId.h>
#include <AzFramework/Input/Channels/InputChannelQuaternion.h>
#include <AzFramework/Input/Contexts/InputContext.h>
#include <AzFramework/Input/Contexts/InputContextComponent.h>
#include <AzFramework/Input/Devices/Gamepad/InputDeviceGamepad.h>
#include <AzFramework/Input/Devices/InputDevice.h>
#include <AzFramework/Input/Devices/InputDeviceId.h>
#include <AzFramework/Input/Devices/Keyboard/InputDeviceKeyboard.h>
#include <AzFramework/Input/Devices/Keyboard/InputDeviceKeyboardWindowsScanCodes.h>
#include <AzFramework/Input/Devices/Motion/InputDeviceMotion.h>
#include <AzFramework/Input/Devices/Mouse/InputDeviceMouse.h>
#include <AzFramework/Input/Devices/Touch/InputDeviceTouch.h>
#include <AzFramework/Input/Devices/VirtualKeyboard/InputDeviceVirtualKeyboard.h>
#include <AzFramework/Input/Events/InputChannelEventFilter.h>
#include <AzFramework/Input/Events/InputChannelEventListener.h>
#include <AzFramework/Input/Events/InputChannelEventSink.h>
#include <AzFramework/Input/Events/InputTextEventListener.h>
#include <AzFramework/Input/Mappings/InputMapping.h>
#include <AzFramework/Input/Mappings/InputMappingAnd.h>
#include <AzFramework/Input/Mappings/InputMappingOr.h>
#include <AzFramework/Input/System/InputSystemComponent.h>
#include <AzFramework/Input/User/LocalUserId.h>
#include <AzFramework/Input/Utils/AdjustAnalogInputForDeadZone.h>
#include <AzFramework/Input/Utils/IsAnyKeyOrButton.h>
#include <AzFramework/Input/Utils/ProcessRawInputEventQueues.h>
#include <AzFramework/IO/FileOperations.h>
#include <AzFramework/IO/LocalFileIO.h>
#include <AzFramework/IO/RemoteFileIO.h>
#include <AzFramework/IO/RemoteStorageDrive.h>
#include <AzFramework/Logging/LogFile.h>
#include <AzFramework/Logging/LoggingComponent.h>
#include <AzFramework/Logging/MissingAssetLogger.h>
#include <AzFramework/Logging/MissingAssetNotificationBus.h>
#include <AzFramework/Logging/StartupLogSinkReporter.h>
#include <AzFramework/Math/InterpolationSample.h>
#include <AzFramework/Metrics/MetricsPlainTextNameRegistration.h>
#include <AzFramework/Network/AssetProcessorConnection.h>
#include <AzFramework/Network/IRemoteTools.h>
#include <AzFramework/Network/SocketConnection.h>
#include <AzFramework/PaintBrush/PaintBrush.h>
#include <AzFramework/PaintBrush/PaintBrushNotificationBus.h>
#include <AzFramework/PaintBrush/PaintBrushSessionBus.h>
#include <AzFramework/PaintBrush/PaintBrushSettings.h>
#include <AzFramework/PaintBrush/PaintBrushSystemComponent.h>
#include <AzFramework/Physics/AnimationConfiguration.h>
#include <AzFramework/Physics/Character.h>
#include <AzFramework/Physics/CharacterBus.h>
#include <AzFramework/Physics/CharacterPhysicsDataBus.h>
#include <AzFramework/Physics/ClassConverters.h>
#include <AzFramework/Physics/ColliderComponentBus.h>
#include <AzFramework/Physics/Collision/CollisionEvents.h>
#include <AzFramework/Physics/Collision/CollisionGroups.h>
#include <AzFramework/Physics/Collision/CollisionLayers.h>
#include <AzFramework/Physics/CollisionBus.h>
#include <AzFramework/Physics/Common/PhysicsEvents.h>
#include <AzFramework/Physics/Common/PhysicsJoint.h>
#include <AzFramework/Physics/Common/PhysicsSceneQueries.h>
#include <AzFramework/Physics/Common/PhysicsSimulatedBody.h>
#include <AzFramework/Physics/Common/PhysicsSimulatedBodyAutomation.h>
#include <AzFramework/Physics/Common/PhysicsSimulatedBodyEvents.h>
#include <AzFramework/Physics/Common/PhysicsTypes.h>
#include <AzFramework/Physics/Components/SimulatedBodyComponentBus.h>
#include <AzFramework/Physics/Configuration/CollisionConfiguration.h>
#include <AzFramework/Physics/Configuration/JointConfiguration.h>
#include <AzFramework/Physics/Configuration/RigidBodyConfiguration.h>
#include <AzFramework/Physics/Configuration/SceneConfiguration.h>
#include <AzFramework/Physics/Configuration/SimulatedBodyConfiguration.h>
#include <AzFramework/Physics/Configuration/StaticRigidBodyConfiguration.h>
#include <AzFramework/Physics/Configuration/SystemConfiguration.h>
#include <AzFramework/Physics/DebugDraw/CharacterPhysicsDebugDraw.h>
#include <AzFramework/Physics/HeightfieldProviderBus.h>
#include <AzFramework/Physics/Material/PhysicsMaterial.h>
#include <AzFramework/Physics/Material/PhysicsMaterialAsset.h>
#include <AzFramework/Physics/Material/PhysicsMaterialId.h>
#include <AzFramework/Physics/Material/PhysicsMaterialManager.h>
#include <AzFramework/Physics/Material/PhysicsMaterialPropertyValue.h>
#include <AzFramework/Physics/Material/PhysicsMaterialSlots.h>
#include <AzFramework/Physics/Material/PhysicsMaterialSystemComponent.h>
#include <AzFramework/Physics/NameConstants.h>
#include <AzFramework/Physics/PhysicsScene.h>
#include <AzFramework/Physics/PhysicsSystem.h>
#include <AzFramework/Physics/Ragdoll.h>
#include <AzFramework/Physics/RagdollPhysicsBus.h>
#include <AzFramework/Physics/RigidBodyBus.h>
#include <AzFramework/Physics/Shape.h>
#include <AzFramework/Physics/ShapeConfiguration.h>
#include <AzFramework/Physics/SimulatedBodies/RigidBody.h>
#include <AzFramework/Physics/SimulatedBodies/StaticRigidBody.h>
#include <AzFramework/Physics/SystemBus.h>
#include <AzFramework/Physics/Utils.h>
#include <AzFramework/Physics/WindBus.h>
#include <AzFramework/Platform/PlatformDefaults.h>
#include <AzFramework/Process/ProcessCommon_fwd.h>
#include <AzFramework/Process/ProcessCommunicator.h>
#include <AzFramework/Process/ProcessCommunicatorTracePrinter.h>
#include <AzFramework/Process/ProcessUtils.h>
#include <AzFramework/Process/ProcessWatcher.h>
#include <AzFramework/ProjectManager/ProjectManager.h>
#include <AzFramework/Quality/QualityCVarGroup.h>
#include <AzFramework/Quality/QualitySystemBus.h>
#include <AzFramework/Quality/QualitySystemComponent.h>
#include <AzFramework/Render/GameIntersectorComponent.h>
#include <AzFramework/Render/GeometryIntersectionBus.h>
#include <AzFramework/Render/GeometryIntersectionStructures.h>
#include <AzFramework/Render/Intersector.h>
#include <AzFramework/Render/IntersectorInterface.h>
#include <AzFramework/Render/RenderSystemBus.h>
#include <AzFramework/Scene/Scene.h>
#include <AzFramework/Scene/SceneSystemComponent.h>
#include <AzFramework/Scene/SceneSystemInterface.h>
#include <AzFramework/Script/ScriptComponent.h>
#include <AzFramework/Script/ScriptDebugAgentBus.h>
#include <AzFramework/Script/ScriptDebugMsgReflection.h>
#include <AzFramework/Script/ScriptRemoteDebugging.h>
#include <AzFramework/Script/ScriptRemoteDebuggingConstants.h>
#include <AzFramework/Slice/SliceEntityBus.h>
#include <AzFramework/Slice/SliceInstantiationBus.h>
#include <AzFramework/Slice/SliceInstantiationTicket.h>
#include <AzFramework/Spawnable/InMemorySpawnableAssetContainer.h>
#include <AzFramework/Spawnable/RootSpawnableInterface.h>
#include <AzFramework/Spawnable/Script/SpawnableScriptAssetRef.h>
#include <AzFramework/Spawnable/Script/SpawnableScriptBus.h>
#include <AzFramework/Spawnable/Script/SpawnableScriptMediator.h>
#include <AzFramework/Spawnable/Script/SpawnableScriptNotificationsHandler.h>
#include <AzFramework/Spawnable/Spawnable.h>
#include <AzFramework/Spawnable/SpawnableAssetBus.h>
#include <AzFramework/Spawnable/SpawnableAssetHandler.h>
#include <AzFramework/Spawnable/SpawnableAssetUtils.h>
#include <AzFramework/Spawnable/SpawnableEntitiesContainer.h>
#include <AzFramework/Spawnable/SpawnableEntitiesInterface.h>
#include <AzFramework/Spawnable/SpawnableEntitiesManager.h>
#include <AzFramework/Spawnable/SpawnableMetaData.h>
#include <AzFramework/Spawnable/SpawnableMonitor.h>
#include <AzFramework/Spawnable/SpawnableSystemComponent.h>
#include <AzFramework/StreamingInstall/StreamingInstall.h>
#include <AzFramework/StreamingInstall/StreamingInstallNotifications.h>
#include <AzFramework/StreamingInstall/StreamingInstallRequests.h>
#include <AzFramework/StringFunc/StringFunc.h>
#include <AzFramework/SurfaceData/SurfaceData.h>
#include <AzFramework/Terrain/TerrainDataRequestBus.h>
#include <AzFramework/Thermal/ThermalInfo.h>
#include <AzFramework/UnitTest/FrameworkTestTypes.h>
#include <AzFramework/UnitTest/TestDebugDisplayRequests.h>
#include <AzFramework/Viewport/CameraInput.h>
#include <AzFramework/Viewport/CameraState.h>
#include <AzFramework/Viewport/ClickDetector.h>
#include <AzFramework/Viewport/CursorState.h>
#include <AzFramework/Viewport/MultiViewportController.h>
#include <AzFramework/Viewport/ScreenGeometry.h>
#include <AzFramework/Viewport/SingleViewportController.h>
#include <AzFramework/Viewport/ViewportBus.h>
#include <AzFramework/Viewport/ViewportColors.h>
#include <AzFramework/Viewport/ViewportConstants.h>
#include <AzFramework/Viewport/ViewportControllerInterface.h>
#include <AzFramework/Viewport/ViewportControllerList.h>
#include <AzFramework/Viewport/ViewportId.h>
#include <AzFramework/Viewport/ViewportScreen.h>
#include <AzFramework/Visibility/BoundsBus.h>
#include <AzFramework/Visibility/EntityBoundsUnionBus.h>
#include <AzFramework/Visibility/EntityVisibilityBoundsUnionSystem.h>
#include <AzFramework/Visibility/EntityVisibilityQuery.h>
#include <AzFramework/Visibility/IVisibilitySystem.h>
#include <AzFramework/Visibility/OcclusionBus.h>
#include <AzFramework/Visibility/OctreeSystemComponent.h>
#include <AzFramework/Visibility/VisibilityDebug.h>
#include <AzFramework/Visibility/VisibleGeometryBus.h>
#include <AzFramework/Windowing/NativeWindow.h>
#include <AzFramework/Windowing/WindowBus.h>
