/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

#pragma once

#include <AzCore/base.h>

//! Precomputed tables shared by the AzCore color types.
//!
//! Every table here is generated by a constexpr function rather than being pasted in as literals, so
//! the transfer function that produced it stays visible and reviewable. This is the home for future
//! tables too (u16 sRGB, PQ/HLG transfer curves, blackbody color temperature, tonemap curves) rather
//! than letting them accrete as one-off statics next to their call sites.
namespace AZ::Internal
{
    //! x raised to an integer power, by repeated squaring.
    constexpr double ConstexprIntPow(double base, int exponent)
    {
        double result = 1.0;
        double factor = base;
        for (int remaining = exponent; remaining > 0; remaining >>= 1)
        {
            if ((remaining & 1) != 0)
            {
                result *= factor;
            }
            factor *= factor;
        }
        return result;
    }

    //! Fifth root by Newton's method, for a in [0, 1].
    //!
    //! Iterating y <- (4y + a/y^4) / 5 converges on a^(1/5). Starting from 1.0 the first phase decays
    //! geometrically by 4/5 per step and the second converges quadratically, so a fixed iteration
    //! count comfortably covers the whole input range; the loop also exits early once it stops moving.
    constexpr double ConstexprFifthRoot(double a)
    {
        if (a <= 0.0)
        {
            return 0.0;
        }

        double y = 1.0;
        for (int i = 0; i < 200; ++i)
        {
            const double y4 = y * y * y * y;
            const double next = (4.0 * y + a / y4) / 5.0;
            const double delta = next > y ? next - y : y - next;
            y = next;
            if (delta <= 1.0e-17 * y)
            {
                break;
            }
        }
        return y;
    }

    //! x^2.4, the exponent the sRGB transfer function needs.
    //!
    //! Expressed as (x^12)^(1/5) because 2.4 == 12/5. That keeps the whole thing to integer powers
    //! plus one Newton iteration, avoiding a constexpr exp/log pair and the precision loss that
    //! composing them would bring.
    constexpr double ConstexprPow24(double x)
    {
        return ConstexprFifthRoot(ConstexprIntPow(x, 12));
    }

    //! The exact sRGB electro-optical transfer function, gamma encoded to linear.
    //! https://www.w3.org/Graphics/Color/srgb
    constexpr double SrgbGammaToLinearExact(double gamma)
    {
        return gamma <= 0.04045 ? (gamma / 12.92) : ConstexprPow24((gamma + 0.055) / 1.055);
    }

    //! Maps each of the 256 gamma encoded byte values to its linear float equivalent.
    //!
    //! AZ::Color::ConvertSrgbGammaToLinear cannot be constexpr because it calls pow() in double, so
    //! this table is what lets the packed color types do sRGB conversion at compile time. It is also
    //! faster at runtime: a 1 KiB lookup instead of a pow().
    struct SrgbToLinearTable
    {
        float m_values[256];
    };

    constexpr SrgbToLinearTable BuildSrgbToLinearTable()
    {
        SrgbToLinearTable table{};
        for (int i = 0; i < 256; ++i)
        {
            table.m_values[i] = static_cast<float>(SrgbGammaToLinearExact(static_cast<double>(i) / 255.0));
        }
        return table;
    }

    inline constexpr SrgbToLinearTable g_srgbToLinearU8 = BuildSrgbToLinearTable();

    //! Converts a gamma encoded byte to linear, exactly, at compile time or at runtime.
    constexpr float SrgbU8ToLinear(u8 gamma)
    {
        return g_srgbToLinearU8.m_values[gamma];
    }

    //! Converts a linear value to the nearest gamma encoded byte.
    //!
    //! Runs a binary search over the same table rather than evaluating the inverse transfer function,
    //! which makes it exact by construction for round tripping and keeps it usable in a constant
    //! expression. Ties resolve to whichever neighbour is actually closer in linear space.
    constexpr u8 LinearToSrgbU8(float linear)
    {
        if (!(linear > 0.0f)) // ordered so that NaN lands here rather than falling through
        {
            return 0;
        }
        if (linear >= 1.0f)
        {
            return 255;
        }

        int low = 0;
        int high = 255;
        while (low < high)
        {
            const int mid = (low + high) / 2;
            if (g_srgbToLinearU8.m_values[mid] < linear)
            {
                low = mid + 1;
            }
            else
            {
                high = mid;
            }
        }

        // `low` is the first entry >= linear; the true nearest is either it or its predecessor.
        if (low > 0)
        {
            const float above = g_srgbToLinearU8.m_values[low];
            const float below = g_srgbToLinearU8.m_values[low - 1];
            if ((above - linear) > (linear - below))
            {
                return static_cast<u8>(low - 1);
            }
        }
        return static_cast<u8>(low);
    }
} // namespace AZ::Internal
