#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#

set(AZSLC_ADVANCED_TEST_FILES
    Advanced/binding-dependencies.py
    Advanced/build-shaders.py
    Advanced/build-variants.py
    Advanced/compute-entries.py
    Advanced/emission-full.py
    Advanced/emission-tester.py
    Advanced/enumerator-type.py
    Advanced/function-overloading.py
    Advanced/inheritance-lookup-seenats.py
    Advanced/input-assembler.py
    Advanced/mae-methodcall.py
    Advanced/ms-to-noms-emission-tester.py
    Advanced/multiple-attribute-namespaces.py
    Advanced/options.py
    Advanced/output-merger.py
    Advanced/pad-to-attribute-validation.py
    Advanced/qualified-type-ref-of-var.py
    Advanced/respect-emit-preprocessor-line-directives.py
    Advanced/seenat.py
    Advanced/srg-categories.py
    Advanced/srg-inlineconsts.py
    Advanced/srg-layout-merged.py
    Advanced/srg-layouts.py
    Advanced/srg-semantics.py
    Advanced/srg-strip-unused.py
    Advanced/symbol-table.py
    Advanced/typeof-vardecl-udt.py
    Advanced/unbounded-arrays-emission-tester.py
)

set(AZSLC_EMISSION_TEST_FILES
    Emission/attribute-specifiers-azsl.azsl
    Emission/attribute-specifiers-hlsl.azsl
    Emission/attribute-specifiers.azsl
    Emission/complete-cs.azsl
    Emission/comprehensive.azsl
    Emission/deep-mutated-reference-renaming.azsl
    Emission/default-argumentvalue-complex.azsl
    Emission/deported-method.azsl
    Emission/double-emission-static-sampler-antiregress.azsl
    Emission/dynamic-sampler-srg.azsl
    Emission/empty-implicit-srg.azsl
    Emission/FrequencyHonor.azsl
    Emission/func-qualifiers.azsl
    Emission/function-modifiers.azsl
    Emission/function-overloaded-migrated.azsl
    Emission/function-with-inout-argument.azsl
    Emission/generic-type-returntype.azsl
    Emission/geometry-modifiers.azsl
    Emission/gmem-depth-mt.azsl
    Emission/gmem-depth-vk.azsl
    Emission/gmem-no-subpass-input.azsl
    Emission/gmem-offset.azsl
    Emission/gmem.azsl
    Emission/infuncbody-vardecl-type-mutations.azsl
    Emission/interpolation-modifiers.azsl
    Emission/library-subobjects.azsl
    Emission/linedirective-beforerename.azsl
    Emission/linedirective-invasive.azsl
    Emission/mat33_padding_run_with_no-alignment-validation.azsl
    Emission/mesh-shader-microsoft-sample.azsl
    Emission/multilevel.azsl
    Emission/name-collision-avoidance.azsl
    Emission/nested-emission.azsl
    Emission/no_specialization-attribute.azsl
    Emission/not-found-type.azsl
    Emission/option-range.azsl
    Emission/ordering-cycle-antiregress.azsl
    Emission/ordering-cycle-antiregress2nd.azsl
    Emission/ordering-cycle-antiregress3rd.azsl
    Emission/ordering-cycle-antiregress4th.azsl
    Emission/ordering-cycle-antiregress5th.azsl
    Emission/ordering-deepnestbug-antiregress.azsl
    Emission/ordering-srg-function.azsl
    Emission/ordering.azsl
    Emission/original-migrated-decl-mutated.azsl
    Emission/original-migrated-decl-skipped.azsl
    Emission/output-attribute.azsl
    Emission/overloads.azsl
    Emission/pad-antiregression-float2x2srgcst.azsl
    Emission/partial-srg.azsl
    Emission/qualified-typealias.azsl
    Emission/ray-tracing-hello-world.azsl
    Emission/ray-tracing-procedural-geometry.azsl
    Emission/ray-tracing-simple-lighting.azsl
    Emission/root-constants-padding-1.azsl
    Emission/root-constants-padding-2.azsl
    Emission/RootSig.azsl
    Emission/RootSigUnique.azsl
    Emission/specialization-constants-dx12.azsl
    Emission/specialization-constants-vk.azsl
    Emission/srg-function-deported-symboltracking.azsl
    Emission/srg-layouts-multiple-unbounded-arrays.azsl
    Emission/static-method-regression.azsl
    Emission/staticconst-srg.azsl
    Emission/typealias-composed.azsl
    Emission/typealias-origin-removed.azsl
    Emission/typealias.azsl
    Emission/undefined-func-om.azsl
    Emission/undefined-func.azsl
    Emission/unnamed-arg-w-semantic.azsl
    Emission/unnamed-arguments.azsl
    Emission/vardecl-translated-initializer.azsl
    Emission/Variants.azsl
)

set(AZSLC_EMISSION_ERROR_TEST_FILES
    Emission/AsError/mat33_padding.azsl
    Emission/AsError/matRC_padding.azsl
    Emission/AsError/undefined-srg-function.azsl
    Emission/AsError/undefined-srg-variable.azsl
)

set(AZSLC_SAMPLE_TEST_FILES
    Samples/Enumeration.azsl
    Samples/PixelShaderOutput.azsl
    Samples/PixelShaderOutputAttributes.azsl
    Samples/VariantsRanges.azsl
    Samples/VariantsReorder.azsl
)

set(AZSLC_SAMPLE_ERROR_TEST_FILES
    Samples/AsError/function_declared_in_struct.azsl
    Samples/AsError/function_defined_in_struct.azsl
    Samples/AsError/inline-const-reserved.azsl
    Samples/AsError/int-no-range.azsl
    Samples/AsError/int-range-bad-max.azsl
    Samples/AsError/int-range-bad-min.azsl
    Samples/AsError/int-range-no-args.azsl
    Samples/AsError/int-range-swapped.azsl
    Samples/AsError/option-invalid-type.azsl
    Samples/AsError/wip-partial-double-srg.azsl
)

set(AZSLC_SEMANTIC_TEST_FILES
    Semantic/16bit-scalar.azsl
    Semantic/array-dimension.azsl
    Semantic/associated-return-type.azsl
    Semantic/class-inheritance-hidden-inherited-member-access.azsl
    Semantic/class-inheritance-inherited-member-access-sro.azsl
    Semantic/class-inheritance.azsl
    Semantic/combined-vardecl-udt.azsl
    Semantic/compiler-extensions-print-symbol.azsl
    Semantic/constantfolding-printout.azsl
    Semantic/cs-group.azsl
    Semantic/deep-inheritance-symbol-access.azsl
    Semantic/deported-method-hard.azsl
    Semantic/deported-method-overqualified-def.azsl
    Semantic/fallback-no-options.azsl
    Semantic/forstatement-nondeclarative-first-clause.azsl
    Semantic/func-redecl-merge-regress.azsl
    Semantic/func-redecl-named-param-shouldnt-error.azsl
    Semantic/function-redeclaration-fullcorrect-sema.azsl
    Semantic/function-signatures.azsl
    Semantic/global-variables-pass.azsl
    Semantic/inheritance-diamond-ok.azsl
    Semantic/interface-inherit.azsl
    Semantic/interface-member-semantic.azsl
    Semantic/interface-multiple-members.azsl
    Semantic/multi-inheritance-symbol-shadowing-qualifiedresolution.azsl
    Semantic/option-qualifier.azsl
    Semantic/overload-resolution-impossible-made-possible.azsl
    Semantic/overload-resolution-impossible-made-possible2.azsl
    Semantic/overload-resolution-impossible-made-possible3.azsl
    Semantic/overload-resolution-impossible-made-possible4.azsl
    Semantic/overloaded-function-definition.azsl
    Semantic/override-keyword.azsl
    Semantic/partial.azsl
    Semantic/qualification-functions.azsl
    Semantic/qualification-printout.azsl
    Semantic/qualification-printout2.azsl
    Semantic/qualification-printout3.azsl
    Semantic/qualification.azsl
    Semantic/shadowed-symbol.azsl
    Semantic/srg-arraydimension.azsl
    Semantic/srg-constant-buffer.azsl
    Semantic/srg-function-deported.azsl
    Semantic/srg-function.azsl
    Semantic/srg-multiple-cb.azsl
    Semantic/srg-pad.azsl
    Semantic/srg-references.azsl
    Semantic/srg-staticmesh.azsl
    Semantic/standardpbr_forwardpass.azsl
    Semantic/symbol-lifetime-out-of-block.azsl
    Semantic/Triangle.azsl
    Semantic/typealias-indirect-reference.azsl
    Semantic/typealias-inline-udt-decl.azsl
    Semantic/typealias-protocol-compliance.azsl
    Semantic/typealias-reference.azsl
    Semantic/typealias-simple.azsl
    Semantic/typeof-keyword.azsl
    Semantic/unbounded-arrays-unique-idx-should-pass-2srgs.azsl
    Semantic/unbounded-arrays-unique-idx-should-pass.azsl
    Semantic/unbounded-arrays1.azsl
    Semantic/unbounded-arrays2.azsl
    Semantic/unbounded-arrays3.azsl
    Semantic/unbounded-arrays4.azsl
    Semantic/unbounded-arrays5.azsl
)

set(AZSLC_SEMANTIC_ERROR_TEST_FILES
    Semantic/AsError/combined-vardecl-udt-funcparam.azsl
    Semantic/AsError/deep-inheritance-diamond-override.azsl
    Semantic/AsError/deportedmethod-and-inline-udt-def.azsl
    Semantic/AsError/deportedmethod-declaration.azsl
    Semantic/AsError/deportedmethod-foreign-class.azsl
    Semantic/AsError/deportedmethod-original-is-not-func.azsl
    Semantic/AsError/deportedmethod-scope-is-not-classtype.azsl
    Semantic/AsError/deportedmethod-undeclared.azsl
    Semantic/AsError/disallowed-function-modifiers.azsl
    Semantic/AsError/disallowed-function-modifiers2.azsl
    Semantic/AsError/disallowed-function-param-qualifier.azsl
    Semantic/AsError/function-different-return-type.azsl
    Semantic/AsError/global-variables.azsl
    Semantic/AsError/identifier-redeclaration.azsl
    Semantic/AsError/inclass-qualified-method-decl.azsl
    Semantic/AsError/inheritance-base-not-declared.azsl
    Semantic/AsError/inheritance-base-not-interface.azsl
    Semantic/AsError/inheritance-multi-concrete-bases.azsl
    Semantic/AsError/inlined-constants-top-level.azsl
    Semantic/AsError/interface-multiple-members-1miss.azsl
    Semantic/AsError/interface-semanticerror-lack-member.azsl
    Semantic/AsError/member-initializer-illformed.azsl
    Semantic/AsError/multi-inheritance-ambiguity.azsl
    Semantic/AsError/multi-inheritance-unsatisfied-override.azsl
    Semantic/AsError/noextend-without-partial-both.azsl
    Semantic/AsError/noextend-without-partial-reverse.azsl
    Semantic/AsError/noextend-without-partial.azsl
    Semantic/AsError/option-in-class.azsl
    Semantic/AsError/option-in-func.azsl
    Semantic/AsError/option-in-srg.azsl
    Semantic/AsError/option-in-struct.azsl
    Semantic/AsError/options-multiple-fallback.azsl
    Semantic/AsError/options-no-fallback.azsl
    Semantic/AsError/overload-mixup-default-argument.azsl
    Semantic/AsError/overload-resolution-impossible-and-heteroreturn.azsl
    Semantic/AsError/override-keyword-nobase.azsl
    Semantic/AsError/override-keyword-noclass.azsl
    Semantic/AsError/pad-to-at-struct-begin.azsl
    Semantic/AsError/pad-to-consecutive.azsl
    Semantic/AsError/pad-to-multi-args.azsl
    Semantic/AsError/pad-to-non-multiple-of-4.azsl
    Semantic/AsError/pad-to-requires-power-of-two.azsl
    Semantic/AsError/pad-to-wrong-args.azsl
    Semantic/AsError/parameter-double-default.azsl
    Semantic/AsError/redef-as-func.azsl
    Semantic/AsError/root-constants-array.azsl
    Semantic/AsError/same-varname-as-type.azsl
    Semantic/AsError/shadowing-within-for.azsl
    Semantic/AsError/srg-arraysize-unfoldable.azsl
    Semantic/AsError/srg-frequency-reuse-2.azsl
    Semantic/AsError/srg-frequency-reuse.azsl
    Semantic/AsError/srg-initializers-illformed.azsl
    Semantic/AsError/srg-no-cb-classes.azsl
    Semantic/AsError/srg-no-enums.azsl
    Semantic/AsError/srg-no-frequency-id.azsl
    Semantic/AsError/srg-no-semantic.azsl
    Semantic/AsError/srg-no-undeclared-cb.azsl
    Semantic/AsError/srg-not-found-arraysize-id.azsl
    Semantic/AsError/srg-partial-nosemantic.azsl
    Semantic/AsError/srg-partial-toomanysemantics.azsl
    Semantic/AsError/srg-wrong-arraysize-id-kind.azsl
    Semantic/AsError/srg-wrong-semantic-name.azsl
    Semantic/AsError/srg-wrong-semantic-type.azsl
    Semantic/AsError/typealias-selfrefer.azsl
    Semantic/AsError/typedef-inlineudt-conflict.azsl
    Semantic/AsError/typedef-typenotfound.azsl
    Semantic/AsError/typeof-double-SRG.azsl
    Semantic/AsError/unknown-option-type.azsl
    Semantic/AsError/vulkan-attributes-constant-id.azsl
    Semantic/AsError/vulkan-attributes-push-constants.azsl
    Semantic/AsError/wip-associated-return-type-incompatible.azsl
    Semantic/AsError/wip-generic-constraint-undeclared.azsl
    Semantic/AsError/wip-interface-semanticerror-lack-member2.azsl
    Semantic/AsError/wip-typealias-undeclared.azsl
)

set(AZSLC_SYNTAX_TEST_FILES
    Syntax/associated-return-type.azsl
    Syntax/attribute-specifiers-comprehensive.azsl
    Syntax/attribute-specifiers-sequence-closure.azsl
    Syntax/attribute-specifiers-standard.azsl
    Syntax/comma-expression.azsl
    Syntax/comma-separated-declarators.azsl
    Syntax/comment-block.azsl
    Syntax/comments.azsl
    Syntax/deportedmethod-and-inline-udt-def.azsl
    Syntax/empty-block-in-block.azsl
    Syntax/empty.azsl
    Syntax/enum-class.azsl
    Syntax/enum.azsl
    Syntax/function-modifiers.azsl
    Syntax/function-redeclaration.azsl
    Syntax/function-signatures.azsl
    Syntax/function-with-block.azsl
    Syntax/function-with-param.azsl
    Syntax/function.azsl
    Syntax/generic-constraint.azsl
    Syntax/generic-function-constraint.azsl
    Syntax/generic-function-multi-constraint-param.azsl
    Syntax/generic-function-multi-constraint.azsl
    Syntax/generic-function-multi.azsl
    Syntax/generic-function-param-unnamed.azsl
    Syntax/generic-function-param.azsl
    Syntax/generic-function.azsl
    Syntax/generic-return-type.azsl
    Syntax/hlsl-semantics.azsl
    Syntax/hlsl.azsl
    Syntax/inherit-scolon.azsl
    Syntax/inherit.azsl
    Syntax/inlined-constants.azsl
    Syntax/interface-parse-scolon.azsl
    Syntax/interface-parse.azsl
    Syntax/just-a-semicolon.azsl
    Syntax/linedirective-anywhere2.azsl
    Syntax/linedirective-simple.azsl
    Syntax/multiple-inheritance.azsl
    Syntax/multiple-inheritance2.azsl
    Syntax/nested-structs.azsl
    Syntax/override.azsl
    Syntax/override2.azsl
    Syntax/partial.azsl
    Syntax/slang.azsl
    Syntax/srg-declaration-arrays.azsl
    Syntax/srg-declaration.azsl
    Syntax/srg-functions.azsl
    Syntax/srg-variables.azsl
    Syntax/typealias.azsl
    Syntax/typedef.azsl
    Syntax/whitespaces.azsl
    Syntax/wip-linedirective-anywhere1.azsl
)

set(AZSLC_SYNTAX_ERROR_TEST_FILES
    Syntax/AsErrors/attribute-arguments-non-literal.azsl
    Syntax/AsErrors/attribute-sequence-keywords.azsl
    Syntax/AsErrors/block-at-top-level.azsl
    Syntax/AsErrors/enumerator-illegal-decl.azsl
    Syntax/AsErrors/function-nested.azsl
    Syntax/AsErrors/function-not-defined-nor-declared.azsl
    Syntax/AsErrors/function-not-defined-rust.azsl
    Syntax/AsErrors/garbage-stream.azsl
    Syntax/AsErrors/garbage-stream2.azsl
    Syntax/AsErrors/line-directive-illformed1.azsl
    Syntax/AsErrors/multi-level-inheritance-interf.azsl
    Syntax/AsErrors/no-struct-inherit.azsl
    Syntax/AsErrors/pad-to-in-function.azsl
    Syntax/AsErrors/srg-no-classes.azsl
    Syntax/AsErrors/srg-no-semantic-body.azsl
    Syntax/AsErrors/typealias-syntax-error.azsl
    Syntax/AsErrors/unexpected-associatedType.azsl
    Syntax/AsErrors/unexpected-typealias.azsl
    Syntax/AsErrors/unnamed-variable-in-body.azsl
    Syntax/AsErrors/unnamed-variable.azsl
)
