#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/Maestro/Components/EditorSequenceAgentComponent.h
    Source/Maestro/Components/EditorSequenceAgentComponent.cpp
    Source/Maestro/Components/EditorSequenceComponent.h
    Source/Maestro/Components/EditorSequenceComponent.cpp
    Source/Maestro/Editor/AnimationContext.h
    Source/Maestro/Editor/AnimationContext.cpp
    Source/Maestro/Editor/TrackViewNewSequenceDialog.h
    Source/Maestro/Editor/TrackViewNewSequenceDialog.cpp
    Source/Maestro/Editor/TrackViewNewSequenceDialog.ui
    Source/Maestro/Editor/SelectSequenceDialog.h
    Source/Maestro/Editor/SelectSequenceDialog.cpp
    Source/Maestro/Editor/SelectLightAnimationDialog.h
    Source/Maestro/Editor/SelectLightAnimationDialog.cpp
    Source/Maestro/Editor/FBXExporterDialog.h
    Source/Maestro/Editor/FBXExporterDialog.cpp
    Source/Maestro/Editor/FBXExporterDialog.ui
    Source/Maestro/Editor/TrackView/AtomOutputFrameCapture.cpp
    Source/Maestro/Editor/TrackView/AtomOutputFrameCapture.h
    Source/Maestro/Editor/TrackView/Legacy/trackview.bmp
    Source/Maestro/Editor/TrackView/Legacy/trackview1.bmp
    Source/Maestro/Editor/TrackView/Legacy/trackview_key.bmp
    Source/Maestro/Editor/TrackView/Legacy/trackview_keys.bmp
    Source/Maestro/Editor/TrackView/Legacy/trackview_nodes.bmp
    Source/Maestro/Editor/TrackView/Legacy/trackview_play.bmp
    Source/Maestro/Editor/TrackView/Legacy/trackview_view.bmp
    Source/Maestro/Editor/TrackView/TrackViewDialog.cpp
    Source/Maestro/Editor/TrackView/TrackViewDialog.h
    Source/Maestro/Editor/TrackView/TrackViewDopeSheetBase.cpp
    Source/Maestro/Editor/TrackView/TrackViewDopeSheetBase.h
    Source/Maestro/Editor/TrackView/TrackViewDoubleSpinBox.cpp
    Source/Maestro/Editor/TrackView/TrackViewDoubleSpinBox.h
    Source/Maestro/Editor/TrackView/TrackViewPythonFuncs.h
    Source/Maestro/Editor/TrackView/TrackViewPythonFuncs.cpp
    Source/Maestro/Editor/TrackView/TrackViewSequenceManager.cpp
    Source/Maestro/Editor/TrackView/TrackViewSequenceManager.h
    Source/Maestro/Editor/TrackView/CommentNodeAnimator.cpp
    Source/Maestro/Editor/TrackView/DirectorNodeAnimator.cpp
    Source/Maestro/Editor/TrackView/CommentNodeAnimator.h
    Source/Maestro/Editor/TrackView/DirectorNodeAnimator.h
    Source/Maestro/Editor/TrackView/SequenceBatchRenderDialog.cpp
    Source/Maestro/Editor/TrackView/TrackViewCurveEditor.cpp
    Source/Maestro/Editor/TrackView/TrackViewFindDlg.cpp
    Source/Maestro/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp
    Source/Maestro/Editor/TrackView/TrackViewNodes.cpp
    Source/Maestro/Editor/TrackView/TrackViewNodes.ui
    Source/Maestro/Editor/TrackView/TrackViewSplineCtrl.cpp
    Source/Maestro/Editor/TrackView/TrackViewTimeline.cpp
    Source/Maestro/Editor/TrackView/TVCustomizeTrackColorsDialog.ui
    Source/Maestro/Editor/TrackView/SequenceBatchRenderDialog.h
    Source/Maestro/Editor/TrackView/SequenceBatchRenderDialog.ui
    Source/Maestro/Editor/TrackView/TrackViewCurveEditor.h
    Source/Maestro/Editor/TrackView/TrackViewCurveEditor.ui
    Source/Maestro/Editor/TrackView/TrackViewFindDlg.h
    Source/Maestro/Editor/TrackView/TrackViewFindDlg.ui
    Source/Maestro/Editor/TrackView/TrackViewKeyPropertiesDlg.h
    Source/Maestro/Editor/TrackView/TrackViewNodes.h
    Source/Maestro/Editor/TrackView/TrackViewSplineCtrl.h
    Source/Maestro/Editor/TrackView/TrackViewTimeline.h
    Source/Maestro/Editor/TrackView/TVCustomizeTrackColorsDlg.cpp
    Source/Maestro/Editor/TrackView/TVCustomizeTrackColorsDlg.h
    Source/Maestro/Editor/TrackView/KeyUIControls.h
    Source/Maestro/Editor/TrackView/2DBezierKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/AssetBlendKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/CaptureKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/ConsoleKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/EventKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/GotoKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/SelectKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/SequenceKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/SoundKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/StringKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/TrackEventKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/TrackViewTrackPropsDlg.ui
    Source/Maestro/Editor/TrackView/TVEventsDialog.cpp
    Source/Maestro/Editor/TrackView/TVEventsDialog.ui
    Source/Maestro/Editor/TrackView/TVSequenceProps.cpp
    Source/Maestro/Editor/TrackView/CommentKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/ScreenFaderKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/TimeRangeKeyUIControls.cpp
    Source/Maestro/Editor/TrackView/TVEventsDialog.h
    Source/Maestro/Editor/TrackView/TVSequenceProps.h
    Source/Maestro/Editor/TrackView/TVSequenceProps.ui
    Source/Maestro/Editor/TrackView/TrackViewAnimNode.cpp
    Source/Maestro/Editor/TrackView/TrackViewTrack.cpp
    Source/Maestro/Editor/TrackView/TrackViewNode.cpp
    Source/Maestro/Editor/TrackView/TrackViewSequence.cpp
    Source/Maestro/Editor/TrackView/TrackViewNodeFactories.cpp
    Source/Maestro/Editor/TrackView/TrackViewEventNode.cpp
    Source/Maestro/Editor/TrackView/TrackViewAnimNode.h
    Source/Maestro/Editor/TrackView/TrackViewTrack.h
    Source/Maestro/Editor/TrackView/TrackViewNode.h
    Source/Maestro/Editor/TrackView/TrackViewSequence.h
    Source/Maestro/Editor/TrackView/TrackViewNodeFactories.h
    Source/Maestro/Editor/TrackView/TrackViewEventNode.h
    Source/Maestro/Editor/TrackView/TrackViewMessageBox.cpp
    Source/Maestro/Editor/TrackView/TrackViewMessageBox.h
    Source/Maestro/Editor/TrackView/VectorKeyUIControls.cpp
    Source/Maestro/Editor/TrackViewExportKeyTimeDlg.h
    Source/Maestro/Editor/TrackViewExportKeyTimeDlg.cpp
    Source/Maestro/Editor/TrackViewExportKeyTimeDlg.ui
    Source/Maestro/Editor/TrackViewFBXImportPreviewDialog.h
    Source/Maestro/Editor/TrackViewFBXImportPreviewDialog.cpp
    Source/Maestro/Editor/TrackViewFBXImportPreviewDialog.ui
)
