#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#

set(FILES
        Source/Backend.cpp
        Source/Backend.h
        Source/CodeEmissionMutator.h
        Source/Common.h
        Source/DependencySolver.h
        Source/DependencySolver.tpl
        Source/DiagnosticStream.h
        Source/Emitter.cpp
        Source/Emitter.h
        Source/Emitters/PlatformEmitter_CommonVulkan.cpp
        Source/Emitters/PlatformEmitter_CommonVulkan.h
        Source/Emitters/PlatformEmitter_DX12.cpp
        Source/Emitters/PlatformEmitter_DX12.h
        Source/Emitters/PlatformEmitter_Metal.cpp
        Source/Emitters/PlatformEmitter_Metal.h
        Source/Emitters/PlatformEmitter_Vulkan.cpp
        Source/Emitters/PlatformEmitter_Vulkan.h
        Source/Exception.h
        Source/GenericUtils.h
        Source/Grammar/azslLexer.cpp
        Source/Grammar/azslLexer.g4
        Source/Grammar/azslLexer.h
        Source/Grammar/azslParser.cpp
        Source/Grammar/azslParser.g4
        Source/Grammar/azslParser.h
        Source/Grammar/azslParserBaseListener.cpp
        Source/Grammar/azslParserBaseListener.h
        Source/Grammar/azslParserBaseVisitor.cpp
        Source/Grammar/azslParserBaseVisitor.h
        Source/Grammar/azslParserListener.cpp
        Source/Grammar/azslParserListener.h
        Source/Grammar/azslParserVisitor.cpp
        Source/Grammar/azslParserVisitor.h
        Source/Grammar/Generate.ps1
        Source/HomonymVisitor.h
        Source/IntermediateRepresentation.cpp
        Source/IntermediateRepresentation.h
        Source/JsonBuilder.h
        Source/KindInfo.h
        Source/Listener.cpp
        Source/Listener.h
        Source/Main.cpp
        Source/Mangling.h
        Source/MetaUtils.h
        Source/NewLineCounterStream.h
        Source/PadToAttributeMutator.cpp
        Source/PadToAttributeMutator.h
        Source/PlatformEmitter.cpp
        Source/PlatformEmitter.h
        Source/PredefinedTypes.h
        Source/PreprocessorLineDirectiveFinder.h
        Source/ReflectableEnums.h
        Source/ReflectableEnumsUtils.h
        Source/Reflection.cpp
        Source/Reflection.h
        Source/Registers.h
        Source/ScopeTracker.cpp
        Source/ScopeTracker.h
        Source/SemanticOrchestrator.cpp
        Source/SemanticOrchestrator.h
        Source/StreamableInterface.h
        Source/SubpassInputToTexture2DCodeMutator.cpp
        Source/SubpassInputToTexture2DCodeMutator.h
        Source/SymbolAggregator.cpp
        Source/SymbolAggregator.h
        Source/SymbolTable.cpp
        Source/SymbolTable.h
        Source/SymbolTranslation.cpp
        Source/SymbolTranslation.h
        Source/Texture2DMSto2DCodeMutator.cpp
        Source/Texture2DMSto2DCodeMutator.h
        Source/TokenToAst.h
        Source/Types.h
        Source/UnboundedArraysValidator.cpp
        Source/UnboundedArraysValidator.h
        Source/Utils.h
)
