#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#

set(FILES
    Source/Jolt/Allocator.h
    Source/Jolt/AssetProduct.cpp
    Source/Jolt/AssetProduct.h
    Source/Jolt/AssetBuilderSystem.h
    Source/Jolt/BehaviorReflection.h
    Source/Jolt/Capabilities.cpp
    Source/Jolt/CharacterConfiguration.cpp
    Source/Jolt/CharacterControllerComponent.cpp
    Source/Jolt/CharacterControllerComponent.h
    Source/Jolt/ColliderComponent.cpp
    Source/Jolt/ColliderComponent.h
    Source/Jolt/ComponentDependencyManager.cpp
    Source/Jolt/ComponentDependencyManager.h
    Source/Jolt/ConfigurationSerializer.cpp
    Source/Jolt/ConfigurationSerializer.h
    Source/Jolt/ConstraintComponent.cpp
    Source/Jolt/ConstraintComponent.h
    Source/Jolt/ConstraintComponentConfiguration.cpp
    Source/Jolt/Cooking.cpp
    Source/Jolt/ComponentUtilities.h
    Source/Jolt/CpuComputeQueue.cpp
    Source/Jolt/CpuComputeQueue.h
    Source/Jolt/CustomConstraint.cpp
    Source/Jolt/CustomConstraintInternal.h
    Source/Jolt/CustomConvexShape.cpp
    Source/Jolt/CustomConvexShape.h
    Source/Jolt/CustomShapeInternal.cpp
    Source/Jolt/CustomShapeInternal.h
    Source/Jolt/DebugRenderer.cpp
    Source/Jolt/DebugDraw.cpp
    Source/Jolt/DebugRenderer.h
    Source/Jolt/Diagnostics.cpp
    Source/Jolt/Event.cpp
    Source/Jolt/EventInternal.h
    Source/Jolt/FloatEnvironment.cpp
    Source/Jolt/FloatEnvironment.h
    Source/Jolt/HairInternal.cpp
    Source/Jolt/HairInternal.h
    Source/Jolt/HairComponent.cpp
    Source/Jolt/HairComponent.h
    Source/Jolt/HairComponentConfiguration.cpp
    Source/Jolt/HandleEncoding.h
    Source/Jolt/JobSystem.cpp
    Source/Jolt/JobSystem.h
    Source/Jolt/LayoutChecks.cpp
    Source/Jolt/Material.cpp
    Source/Jolt/MaterialInternal.cpp
    Source/Jolt/MaterialInternal.h
    Source/Jolt/NativeRuntime.cpp
    Source/Jolt/NativeRuntime.h
    Source/Jolt/NativeProfiler.cpp
    Source/Jolt/NativeShapeFactory.cpp
    Source/Jolt/NativeShapeFactory.h
    Source/Jolt/Operation.cpp
    Source/Jolt/OperationInternal.h
    Source/Jolt/Path.cpp
    Source/Jolt/PathComponent.cpp
    Source/Jolt/PathComponent.h
    Source/Jolt/Profiler.h
    Source/Jolt/Query.cpp
    Source/Jolt/Ragdoll.cpp
    Source/Jolt/RagdollComponent.cpp
    Source/Jolt/RagdollComponent.h
    Source/Jolt/RagdollComponentConfiguration.cpp
    Source/Jolt/Reflection.h
    Source/Jolt/RigidBodyComponent.cpp
    Source/Jolt/RigidBodyComponent.h
    Source/Jolt/RigidBodyConfiguration.cpp
    Source/Jolt/Scene.cpp
    Source/Jolt/SceneAsset.cpp
    Source/Jolt/SceneAssetHandler.cpp
    Source/Jolt/SceneAssetHandler.h
    Source/Jolt/SceneComponent.cpp
    Source/Jolt/SceneComponent.h
    Source/Jolt/SceneComponentConfiguration.cpp
    Source/Jolt/System.cpp
    Source/Jolt/SystemInternal.h
    Source/Jolt/TransformedShapeLease.h
    Source/Jolt/StateRecorder.cpp
    Source/Jolt/StateRecorder.h
    Source/Jolt/StateArchive.cpp
    Source/Jolt/StateArchive.h
    Source/Jolt/StaticRigidBodyComponent.cpp
    Source/Jolt/StaticRigidBodyComponent.h
    Source/Jolt/SystemComponent.cpp
    Source/Jolt/SystemComponent.h
    Source/Jolt/SystemConfiguration.cpp
    Source/Jolt/VehicleComponentConfiguration.cpp
    Source/Jolt/VehicleComponents.cpp
    Source/Jolt/VehicleComponents.h
    Source/Jolt/VirtualCharacterControllerComponent.cpp
    Source/Jolt/VirtualCharacterControllerComponent.h
    Source/Jolt/World.cpp
    Source/Jolt/World.h
    Source/Jolt/WorldTypes.cpp
    Source/Jolt/WorldQueryBus.cpp
    Source/Jolt/BodyConfiguration.cpp
    Source/Jolt/Shape.cpp
    Source/Jolt/ShapeConfiguration.cpp
    Source/Jolt/ShapeOwner.cpp
    Source/Jolt/ShapeOwner.h
    Source/Jolt/SoftBodyComponent.cpp
    Source/Jolt/SoftBodyComponent.h
    Source/Jolt/SoftBodyComponentConfiguration.cpp
    Source/Jolt/Skeleton.cpp
    Source/Jolt/SkeletonAsset.cpp
    Source/Jolt/SkeletonAssetHandler.cpp
    Source/Jolt/SkeletonAssetHandler.h
    Source/Jolt/SkeletonComponent.cpp
    Source/Jolt/SkeletonComponent.h
    Source/Jolt/SkeletonComponentConfiguration.cpp
)
