#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#

set(AZSLC_ADVANCED_TEST_FILES
    Advanced/BindingDependencies.py
    Advanced/BuildShaders.py
    Advanced/BuildVariants.py
    Advanced/ComputeEntries.py
    Advanced/EmissionFull.py
    Advanced/EmissionTester.py
    Advanced/EnumeratorType.py
    Advanced/FunctionOverloading.py
    Advanced/InheritanceLookupSeenats.py
    Advanced/InputAssembler.py
    Advanced/MaeMethodcall.py
    Advanced/MsToNomsEmissionTester.py
    Advanced/MultipleAttributeNamespaces.py
    Advanced/Options.py
    Advanced/OutputMerger.py
    Advanced/PadToAttributeValidation.py
    Advanced/QualifiedTypeRefOfVar.py
    Advanced/RespectEmitPreprocessorLineDirectives.py
    Advanced/Seenat.py
    Advanced/SrgCategories.py
    Advanced/SrgInlineconsts.py
    Advanced/SrgLayoutMerged.py
    Advanced/SrgLayouts.py
    Advanced/SrgSemantics.py
    Advanced/SrgStripUnused.py
    Advanced/SymbolTable.py
    Advanced/TypeofVardeclUdt.py
    Advanced/UnboundedArraysEmissionTester.py
)

set(AZSLC_EMISSION_TEST_FILES
    Emission/AttributeSpecifiersAzsl.azsl
    Emission/AttributeSpecifiersHlsl.azsl
    Emission/AttributeSpecifiers.azsl
    Emission/CompleteCs.azsl
    Emission/Comprehensive.azsl
    Emission/DeepMutatedReferenceRenaming.azsl
    Emission/DefaultArgumentvalueComplex.azsl
    Emission/DeportedMethod.azsl
    Emission/DoubleEmissionStaticSamplerAntiregress.azsl
    Emission/DynamicSamplerSrg.azsl
    Emission/EmptyImplicitSrg.azsl
    Emission/Frequencyhonor.azsl
    Emission/FuncQualifiers.azsl
    Emission/FunctionModifiers.azsl
    Emission/FunctionOverloadedMigrated.azsl
    Emission/FunctionWithInoutArgument.azsl
    Emission/GenericTypeReturntype.azsl
    Emission/GeometryModifiers.azsl
    Emission/GmemDepthMt.azsl
    Emission/GmemDepthVk.azsl
    Emission/GmemNoSubpassInput.azsl
    Emission/GmemOffset.azsl
    Emission/Gmem.azsl
    Emission/InfuncbodyVardeclTypeMutations.azsl
    Emission/InterpolationModifiers.azsl
    Emission/LibrarySubobjects.azsl
    Emission/LinedirectiveBeforerename.azsl
    Emission/LinedirectiveInvasive.azsl
    Emission/Mat33PaddingRunWithNoAlignmentValidation.azsl
    Emission/MeshShaderMicrosoftSample.azsl
    Emission/Multilevel.azsl
    Emission/NameCollisionAvoidance.azsl
    Emission/NestedEmission.azsl
    Emission/NoSpecializationAttribute.azsl
    Emission/NotFoundType.azsl
    Emission/OptionRange.azsl
    Emission/OrderingCycleAntiregress.azsl
    Emission/OrderingCycleAntiregress2nd.azsl
    Emission/OrderingCycleAntiregress3rd.azsl
    Emission/OrderingCycleAntiregress4th.azsl
    Emission/OrderingCycleAntiregress5th.azsl
    Emission/OrderingDeepnestbugAntiregress.azsl
    Emission/OrderingSrgFunction.azsl
    Emission/Ordering.azsl
    Emission/OriginalMigratedDeclMutated.azsl
    Emission/OriginalMigratedDeclSkipped.azsl
    Emission/OutputAttribute.azsl
    Emission/Overloads.azsl
    Emission/PadAntiregressionFloat2x2srgcst.azsl
    Emission/PartialSrg.azsl
    Emission/QualifiedTypealias.azsl
    Emission/RayTracingHelloWorld.azsl
    Emission/RayTracingProceduralGeometry.azsl
    Emission/RayTracingSimpleLighting.azsl
    Emission/RootConstantsPadding1.azsl
    Emission/RootConstantsPadding2.azsl
    Emission/Rootsig.azsl
    Emission/Rootsigunique.azsl
    Emission/SpecializationConstantsDx12.azsl
    Emission/SpecializationConstantsVk.azsl
    Emission/SrgFunctionDeportedSymboltracking.azsl
    Emission/SrgLayoutsMultipleUnboundedArrays.azsl
    Emission/StaticMethodRegression.azsl
    Emission/StaticconstSrg.azsl
    Emission/TypealiasComposed.azsl
    Emission/TypealiasOriginRemoved.azsl
    Emission/Typealias.azsl
    Emission/UndefinedFuncOm.azsl
    Emission/UndefinedFunc.azsl
    Emission/UnnamedArgWSemantic.azsl
    Emission/UnnamedArguments.azsl
    Emission/VardeclTranslatedInitializer.azsl
    Emission/Variants.azsl
)

set(AZSLC_EMISSION_ERROR_TEST_FILES
    Emission/Error/Mat33Padding.azsl
    Emission/Error/MatrcPadding.azsl
    Emission/Error/UndefinedSrgFunction.azsl
    Emission/Error/UndefinedSrgVariable.azsl
)

set(AZSLC_SAMPLE_TEST_FILES
    Samples/Enumeration.azsl
    Samples/Pixelshaderoutput.azsl
    Samples/Pixelshaderoutputattributes.azsl
    Samples/Variantsranges.azsl
    Samples/Variantsreorder.azsl
)

set(AZSLC_SAMPLE_ERROR_TEST_FILES
    Samples/Error/FunctionDeclaredInStruct.azsl
    Samples/Error/FunctionDefinedInStruct.azsl
    Samples/Error/InlineConstReserved.azsl
    Samples/Error/IntNoRange.azsl
    Samples/Error/IntRangeBadMax.azsl
    Samples/Error/IntRangeBadMin.azsl
    Samples/Error/IntRangeNoArgs.azsl
    Samples/Error/IntRangeSwapped.azsl
    Samples/Error/OptionInvalidType.azsl
    Samples/Error/WipPartialDoubleSrg.azsl
)

set(AZSLC_SEMANTIC_TEST_FILES
    Semantic/16BitScalar.azsl
    Semantic/ArrayDimension.azsl
    Semantic/AssociatedReturnType.azsl
    Semantic/ClassInheritanceHiddenInheritedMemberAccess.azsl
    Semantic/ClassInheritanceInheritedMemberAccessSro.azsl
    Semantic/ClassInheritance.azsl
    Semantic/CombinedVardeclUdt.azsl
    Semantic/CompilerExtensionsPrintSymbol.azsl
    Semantic/ConstantfoldingPrintout.azsl
    Semantic/CsGroup.azsl
    Semantic/DeepInheritanceSymbolAccess.azsl
    Semantic/DeportedMethodHard.azsl
    Semantic/DeportedMethodOverqualifiedDef.azsl
    Semantic/FallbackNoOptions.azsl
    Semantic/ForstatementNondeclarativeFirstClause.azsl
    Semantic/FuncRedeclMergeRegress.azsl
    Semantic/FuncRedeclNamedParamShouldntError.azsl
    Semantic/FunctionRedeclarationFullcorrectSema.azsl
    Semantic/FunctionSignatures.azsl
    Semantic/GlobalVariablesPass.azsl
    Semantic/InheritanceDiamondOk.azsl
    Semantic/InterfaceInherit.azsl
    Semantic/InterfaceMemberSemantic.azsl
    Semantic/InterfaceMultipleMembers.azsl
    Semantic/MultiInheritanceSymbolShadowingQualifiedresolution.azsl
    Semantic/OptionQualifier.azsl
    Semantic/OverloadResolutionImpossibleMadePossible.azsl
    Semantic/OverloadResolutionImpossibleMadePossible2.azsl
    Semantic/OverloadResolutionImpossibleMadePossible3.azsl
    Semantic/OverloadResolutionImpossibleMadePossible4.azsl
    Semantic/OverloadedFunctionDefinition.azsl
    Semantic/OverrideKeyword.azsl
    Semantic/Partial.azsl
    Semantic/QualificationFunctions.azsl
    Semantic/QualificationPrintout.azsl
    Semantic/QualificationPrintout2.azsl
    Semantic/QualificationPrintout3.azsl
    Semantic/Qualification.azsl
    Semantic/ShadowedSymbol.azsl
    Semantic/SrgArraydimension.azsl
    Semantic/SrgConstantBuffer.azsl
    Semantic/SrgFunctionDeported.azsl
    Semantic/SrgFunction.azsl
    Semantic/SrgMultipleCb.azsl
    Semantic/SrgPad.azsl
    Semantic/SrgReferences.azsl
    Semantic/SrgStaticmesh.azsl
    Semantic/StandardpbrForwardpass.azsl
    Semantic/SymbolLifetimeOutOfBlock.azsl
    Semantic/Triangle.azsl
    Semantic/TypealiasIndirectReference.azsl
    Semantic/TypealiasInlineUdtDecl.azsl
    Semantic/TypealiasProtocolCompliance.azsl
    Semantic/TypealiasReference.azsl
    Semantic/TypealiasSimple.azsl
    Semantic/TypeofKeyword.azsl
    Semantic/UnboundedArraysUniqueIdxShouldPass2Srgs.azsl
    Semantic/UnboundedArraysUniqueIdxShouldPass.azsl
    Semantic/UnboundedArrays1.azsl
    Semantic/UnboundedArrays2.azsl
    Semantic/UnboundedArrays3.azsl
    Semantic/UnboundedArrays4.azsl
    Semantic/UnboundedArrays5.azsl
)

set(AZSLC_SEMANTIC_ERROR_TEST_FILES
    Semantic/Error/CombinedVardeclUdtFuncparam.azsl
    Semantic/Error/DeepInheritanceDiamondOverride.azsl
    Semantic/Error/DeportedmethodAndInlineUdtDef.azsl
    Semantic/Error/DeportedmethodDeclaration.azsl
    Semantic/Error/DeportedmethodForeignClass.azsl
    Semantic/Error/DeportedmethodOriginalIsNotFunc.azsl
    Semantic/Error/DeportedmethodScopeIsNotClasstype.azsl
    Semantic/Error/DeportedmethodUndeclared.azsl
    Semantic/Error/DisallowedFunctionModifiers.azsl
    Semantic/Error/DisallowedFunctionModifiers2.azsl
    Semantic/Error/DisallowedFunctionParamQualifier.azsl
    Semantic/Error/FunctionDifferentReturnType.azsl
    Semantic/Error/GlobalVariables.azsl
    Semantic/Error/IdentifierRedeclaration.azsl
    Semantic/Error/InclassQualifiedMethodDecl.azsl
    Semantic/Error/InheritanceBaseNotDeclared.azsl
    Semantic/Error/InheritanceBaseNotInterface.azsl
    Semantic/Error/InheritanceMultiConcreteBases.azsl
    Semantic/Error/InlinedConstantsTopLevel.azsl
    Semantic/Error/InterfaceMultipleMembers1Miss.azsl
    Semantic/Error/InterfaceSemanticerrorLackMember.azsl
    Semantic/Error/MemberInitializerIllformed.azsl
    Semantic/Error/MultiInheritanceAmbiguity.azsl
    Semantic/Error/MultiInheritanceUnsatisfiedOverride.azsl
    Semantic/Error/NoextendWithoutPartialBoth.azsl
    Semantic/Error/NoextendWithoutPartialReverse.azsl
    Semantic/Error/NoextendWithoutPartial.azsl
    Semantic/Error/OptionInClass.azsl
    Semantic/Error/OptionInFunc.azsl
    Semantic/Error/OptionInSrg.azsl
    Semantic/Error/OptionInStruct.azsl
    Semantic/Error/OptionsMultipleFallback.azsl
    Semantic/Error/OptionsNoFallback.azsl
    Semantic/Error/OverloadMixupDefaultArgument.azsl
    Semantic/Error/OverloadResolutionImpossibleAndHeteroreturn.azsl
    Semantic/Error/OverrideKeywordNobase.azsl
    Semantic/Error/OverrideKeywordNoclass.azsl
    Semantic/Error/PadToAtStructBegin.azsl
    Semantic/Error/PadToConsecutive.azsl
    Semantic/Error/PadToMultiArgs.azsl
    Semantic/Error/PadToNonMultipleOf4.azsl
    Semantic/Error/PadToRequiresPowerOfTwo.azsl
    Semantic/Error/PadToWrongArgs.azsl
    Semantic/Error/ParameterDoubleDefault.azsl
    Semantic/Error/RedefAsFunc.azsl
    Semantic/Error/RootConstantsArray.azsl
    Semantic/Error/SameVarnameAsType.azsl
    Semantic/Error/ShadowingWithinFor.azsl
    Semantic/Error/SrgArraysizeUnfoldable.azsl
    Semantic/Error/SrgFrequencyReuse2.azsl
    Semantic/Error/SrgFrequencyReuse.azsl
    Semantic/Error/SrgInitializersIllformed.azsl
    Semantic/Error/SrgNoCbClasses.azsl
    Semantic/Error/SrgNoEnums.azsl
    Semantic/Error/SrgNoFrequencyId.azsl
    Semantic/Error/SrgNoSemantic.azsl
    Semantic/Error/SrgNoUndeclaredCb.azsl
    Semantic/Error/SrgNotFoundArraysizeId.azsl
    Semantic/Error/SrgPartialNosemantic.azsl
    Semantic/Error/SrgPartialToomanysemantics.azsl
    Semantic/Error/SrgWrongArraysizeIdKind.azsl
    Semantic/Error/SrgWrongSemanticName.azsl
    Semantic/Error/SrgWrongSemanticType.azsl
    Semantic/Error/TypealiasSelfrefer.azsl
    Semantic/Error/TypedefInlineudtConflict.azsl
    Semantic/Error/TypedefTypenotfound.azsl
    Semantic/Error/TypeofDoubleSrg.azsl
    Semantic/Error/UnknownOptionType.azsl
    Semantic/Error/VulkanAttributesConstantId.azsl
    Semantic/Error/VulkanAttributesPushConstants.azsl
    Semantic/Error/WipAssociatedReturnTypeIncompatible.azsl
    Semantic/Error/WipGenericConstraintUndeclared.azsl
    Semantic/Error/WipInterfaceSemanticerrorLackMember2.azsl
    Semantic/Error/WipTypealiasUndeclared.azsl
)

set(AZSLC_SYNTAX_TEST_FILES
    Syntax/AssociatedReturnType.azsl
    Syntax/AttributeSpecifiersComprehensive.azsl
    Syntax/AttributeSpecifiersSequenceClosure.azsl
    Syntax/AttributeSpecifiersStandard.azsl
    Syntax/CommaExpression.azsl
    Syntax/CommaSeparatedDeclarators.azsl
    Syntax/CommentBlock.azsl
    Syntax/Comments.azsl
    Syntax/DeportedmethodAndInlineUdtDef.azsl
    Syntax/EmptyBlockInBlock.azsl
    Syntax/Empty.azsl
    Syntax/EnumClass.azsl
    Syntax/Enum.azsl
    Syntax/FunctionModifiers.azsl
    Syntax/FunctionRedeclaration.azsl
    Syntax/FunctionSignatures.azsl
    Syntax/FunctionWithBlock.azsl
    Syntax/FunctionWithParam.azsl
    Syntax/Function.azsl
    Syntax/GenericConstraint.azsl
    Syntax/GenericFunctionConstraint.azsl
    Syntax/GenericFunctionMultiConstraintParam.azsl
    Syntax/GenericFunctionMultiConstraint.azsl
    Syntax/GenericFunctionMulti.azsl
    Syntax/GenericFunctionParamUnnamed.azsl
    Syntax/GenericFunctionParam.azsl
    Syntax/GenericFunction.azsl
    Syntax/GenericReturnType.azsl
    Syntax/HlslSemantics.azsl
    Syntax/Hlsl.azsl
    Syntax/InheritScolon.azsl
    Syntax/Inherit.azsl
    Syntax/InlinedConstants.azsl
    Syntax/InterfaceParseScolon.azsl
    Syntax/InterfaceParse.azsl
    Syntax/JustASemicolon.azsl
    Syntax/LinedirectiveAnywhere2.azsl
    Syntax/LinedirectiveSimple.azsl
    Syntax/MultipleInheritance.azsl
    Syntax/MultipleInheritance2.azsl
    Syntax/NestedStructs.azsl
    Syntax/Override.azsl
    Syntax/Override2.azsl
    Syntax/Partial.azsl
    Syntax/Slang.azsl
    Syntax/SrgDeclarationArrays.azsl
    Syntax/SrgDeclaration.azsl
    Syntax/SrgFunctions.azsl
    Syntax/SrgVariables.azsl
    Syntax/Typealias.azsl
    Syntax/Typedef.azsl
    Syntax/Whitespaces.azsl
    Syntax/WipLinedirectiveAnywhere1.azsl
)

set(AZSLC_SYNTAX_ERROR_TEST_FILES
    Syntax/Error/AttributeArgumentsNonLiteral.azsl
    Syntax/Error/AttributeSequenceKeywords.azsl
    Syntax/Error/BlockAtTopLevel.azsl
    Syntax/Error/EnumeratorIllegalDecl.azsl
    Syntax/Error/FunctionNested.azsl
    Syntax/Error/FunctionNotDefinedNorDeclared.azsl
    Syntax/Error/FunctionNotDefinedRust.azsl
    Syntax/Error/GarbageStream.azsl
    Syntax/Error/GarbageStream2.azsl
    Syntax/Error/LineDirectiveIllformed1.azsl
    Syntax/Error/MultiLevelInheritanceInterf.azsl
    Syntax/Error/NoStructInherit.azsl
    Syntax/Error/PadToInFunction.azsl
    Syntax/Error/SrgNoClasses.azsl
    Syntax/Error/SrgNoSemanticBody.azsl
    Syntax/Error/TypealiasSyntaxError.azsl
    Syntax/Error/UnexpectedAssociatedtype.azsl
    Syntax/Error/UnexpectedTypealias.azsl
    Syntax/Error/UnnamedVariableInBody.azsl
    Syntax/Error/UnnamedVariable.azsl
)
