/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

#pragma once

#include <Atom/RPI.Public/Material/MaterialShaderParameterLayout.h>
#include <AzCore/IO/Path/Path.h>
#include <AzCore/std/containers/vector.h>
#include <AzCore/std/string/string.h>
#include <AzCore/std/string/string_view.h>

namespace AZ::RPI
{
    //! Everything the language generator needs to stitch one shader for one (material type x material
    //! pipeline shader-template) pairing. Paths are already resolved to absolute, POSIX-normalized form.
    struct MaterialShaderStitchInputs
    {
        AZStd::string_view m_builderName; //!< Emitted into the "generated by" banner.
        AZStd::string_view m_materialTypeName;
        AZStd::string_view m_parametersFileName; //!< Base file name of the generated material-parameters include.
        AZStd::string_view m_materialTypeDefinesFilePath; //!< Optional material-type #defines include (may be empty).
        AZStd::string_view m_materialTypeShaderCodeFilePath; //!< The material type's authored shader code.
        AZStd::string_view m_shaderTemplateFilePath; //!< The material pipeline's shader template to include last.
        const AZStd::vector<AZStd::string>* m_objectSrgAdditions = nullptr; //!< Optional ObjectSrg member additions.
        const AZStd::vector<AZStd::string>* m_drawSrgAdditions = nullptr; //!< Optional DrawSrg member additions.
    };

    //! Language-specific material shader-code generation. The MaterialTypeBuilder's pipeline stage
    //! turns an abstract material type into concrete shaders by stitching three sources together: the
    //! auto-generated material-parameter struct, the material type's authored shader code, and a
    //! material pipeline's shader template. AZSL and Slang differ only in a few surface details -- the
    //! generated file extensions, the MATERIAL_*_FILE_PATH macro names, and the parameter-struct's
    //! host language -- so those details are the seam. A material pipeline declares which language its
    //! templates are authored in; the material type it renders must match.
    class MaterialShaderGenerator
    {
    public:
        virtual ~MaterialShaderGenerator() = default;

        //! Human-readable language name for diagnostics ("AZSL", "Slang").
        virtual const char* GetLanguageName() const = 0;

        //! Extension (without the dot) of the generated material-parameters include, e.g. "azsli".
        virtual const char* GetParameterFileExtension() const = 0;

        //! Extension (without the dot) of the generated stitched shader source, e.g. "azsl".
        virtual const char* GetShaderFileExtension() const = 0;

        //! Emit the material-parameter struct that @layout describes to @filename.
        virtual bool WriteMaterialParameterStructure(const MaterialShaderParameterLayout& layout, const AZ::IO::Path& filename) const = 0;

        //! Build the full stitched shader source that references the parameter struct, material-type
        //! shader code, and pipeline template. The returned bytes become an intermediate shader source.
        virtual AZStd::string GenerateStitchedShaderSource(const MaterialShaderStitchInputs& inputs) const = 0;
    };

    //! Returns the generator for @languageName ("AZSL" default, "Slang"), or nullptr if unknown.
    const MaterialShaderGenerator* GetMaterialShaderGenerator(AZStd::string_view languageName);
} // namespace AZ::RPI
