/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

#include "MaterialShaderGenerator.h"

#include <AzCore/StringFunc/StringFunc.h>
#include <AzCore/std/string/conversions.h>

namespace AZ::RPI
{
    namespace
    {
        //! Shared stitching used by both language generators. The languages differ only in the
        //! MATERIAL_*_<infix>_FILE_PATH macro names (@macroInfix is "AZSLI" or "SLANGI"); with
        //! "AZSLI" this reproduces the MaterialTypeBuilder's original output byte for byte.
        AZStd::string GenerateStitchedSource(const MaterialShaderStitchInputs& inputs, const char* macroInfix)
        {
            AZStd::string generated;
            generated += AZStd::string::format(
                "// This code was generated by %.*s. Do not modify.\n", AZ_STRING_ARG(inputs.m_builderName));

            if (inputs.m_objectSrgAdditions && !inputs.m_objectSrgAdditions->empty())
            {
                // The #define that injects new ObjectSrg members specified by the material pipelines.
                generated += AZStd::string::format("#define MATERIAL_PIPELINE_OBJECT_SRG_MEMBERS   \\\n");
                for (const AZStd::string& objectSrgAddition : *inputs.m_objectSrgAdditions)
                {
                    generated += AZStd::string::format("%s   \\\n", objectSrgAddition.c_str());
                }
                generated += AZStd::string::format("\n");
            }

            if (inputs.m_drawSrgAdditions && !inputs.m_drawSrgAdditions->empty())
            {
                // The #define that injects new DrawSrg members specified by the material pipelines.
                generated += AZStd::string::format("#define MATERIAL_PIPELINE_DRAW_SRG_MEMBERS   \\\n");
                for (const AZStd::string& drawSrgAddition : *inputs.m_drawSrgAdditions)
                {
                    generated += AZStd::string::format("%s   \\\n", drawSrgAddition.c_str());
                }
                generated += AZStd::string::format("\n");
            }

            generated += AZStd::string::format(
                "#define MATERIAL_PARAMETERS_%s_FILE_PATH \"%.*s\" \n", macroInfix, AZ_STRING_ARG(inputs.m_parametersFileName));

            generated += AZStd::string::format("\n");
            if (!inputs.m_materialTypeDefinesFilePath.empty())
            {
                generated += AZStd::string::format(
                    "#define MATERIAL_TYPE_DEFINES_%s_FILE_PATH \"%.*s\" \n",
                    macroInfix, AZ_STRING_ARG(inputs.m_materialTypeDefinesFilePath));
            }

            generated += AZStd::string::format(
                "#define MATERIAL_TYPE_%s_FILE_PATH \"%.*s\" \n", macroInfix, AZ_STRING_ARG(inputs.m_materialTypeShaderCodeFilePath));

            AZStd::string materialTypeNameUpper(inputs.m_materialTypeName);
            AZStd::to_upper(materialTypeNameUpper.begin(), materialTypeNameUpper.end());
            generated += AZStd::string::format("#define MATERIAL_TYPE_%s 1 \n", materialTypeNameUpper.c_str());

            generated += AZStd::string::format("#include \"%.*s\" \n", AZ_STRING_ARG(inputs.m_shaderTemplateFilePath));

            return generated;
        }

        //! AZSL: the historical material shader-code generation, extracted unchanged.
        class AzslMaterialShaderGenerator final : public MaterialShaderGenerator
        {
        public:
            const char* GetLanguageName() const override { return "AZSL"; }
            const char* GetParameterFileExtension() const override { return "azsli"; }
            const char* GetShaderFileExtension() const override { return "azsl"; }

            bool WriteMaterialParameterStructure(const MaterialShaderParameterLayout& layout, const AZ::IO::Path& filename) const override
            {
                return layout.WriteMaterialParameterStructureAzsli(filename);
            }

            AZStd::string GenerateStitchedShaderSource(const MaterialShaderStitchInputs& inputs) const override
            {
                return GenerateStitchedSource(inputs, "AZSLI");
            }
        };

        //! Slang: same stitch, Slang file extensions and SLANGI macro names. The parameter struct is
        //! host-language-neutral (HLSL scalar/vector/matrix types compile in Slang), so it is emitted
        //! by the same writer, only to a .slangi file.
        class SlangMaterialShaderGenerator final : public MaterialShaderGenerator
        {
        public:
            const char* GetLanguageName() const override { return "Slang"; }
            const char* GetParameterFileExtension() const override { return "slangi"; }
            const char* GetShaderFileExtension() const override { return "slang"; }

            bool WriteMaterialParameterStructure(const MaterialShaderParameterLayout& layout, const AZ::IO::Path& filename) const override
            {
                return layout.WriteMaterialParameterStructureAzsli(filename);
            }

            AZStd::string GenerateStitchedShaderSource(const MaterialShaderStitchInputs& inputs) const override
            {
                return GenerateStitchedSource(inputs, "SLANGI");
            }
        };
    } // namespace

    const MaterialShaderGenerator* GetMaterialShaderGenerator(AZStd::string_view languageName)
    {
        static const AzslMaterialShaderGenerator s_azsl;
        static const SlangMaterialShaderGenerator s_slang;
        if (AZ::StringFunc::Equal(languageName, "Slang"))
        {
            return &s_slang;
        }
        if (languageName.empty() || AZ::StringFunc::Equal(languageName, "AZSL"))
        {
            return &s_azsl;
        }
        return nullptr;
    }
} // namespace AZ::RPI
