/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AzCore Public Precompiled Header
// Contains ALL public AzCore and AZStd headers. Applied as a PUBLIC PCH so that
// all targets depending on AzCore automatically benefit from precompiled headers.
// Controlled by the LY_PCH CMake option (default: ON).

#pragma once

// Standard Library
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <new>
#include <set>
#include <string>
#include <string_view>
#include <thread>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

// ---------------------------------------------------------------------------
// Windows.h macro cleanup
// On Windows, standard library headers (<mutex>, <thread>, <chrono>, etc.)
// may transitively pull in windows.h, which pollutes the global namespace
// with macros that collide with engine identifiers.  These undefs MUST appear
// BEFORE the AzCore headers so declarations are parsed with the correct names.
// Only macros known to conflict with O3DE identifiers are removed here;
// macros like CreateEvent, LoadLibrary, RemoveDirectory etc. are left intact
// because WinAPI implementation files depend on them.
// ---------------------------------------------------------------------------
#ifdef AZ_PLATFORM_WINDOWS
#   ifdef CompareString
#       undef CompareString
#   endif
#   ifdef GetMessage
#       undef GetMessage
#   endif
#   ifdef GetObject
#       undef GetObject
#   endif
#   ifdef GetCommandLine
#       undef GetCommandLine
#   endif
#   ifdef LoadImage
#       undef LoadImage
#   endif
#   ifdef DeleteFile
#       undef DeleteFile
#   endif
#   ifdef GetCurrentTime
#       undef GetCurrentTime
#   endif
#   ifdef SetJob
#       undef SetJob
#   endif
#   ifdef GetForm
#       undef GetForm
#   endif
#   ifdef DispatchMessage
#       undef DispatchMessage
#   endif
#   ifdef SendMessage
#       undef SendMessage
#   endif
#   ifdef Yield
#       undef Yield
#   endif
#endif // AZ_PLATFORM_WINDOWS

#include <AzCore/Asset/AssetCommon.h>
#include <AzCore/Asset/AssetContainer.h>
#include <AzCore/Asset/AssetDataStream.h>
#include <AzCore/Asset/AssetJsonSerializer.h>
#include <AzCore/Asset/AssetManager.h>
#include <AzCore/Asset/AssetManagerBus.h>
#include <AzCore/Asset/AssetManagerComponent.h>
#include <AzCore/Asset/AssetSerializer.h>
#include <AzCore/Asset/AssetTypeInfoBus.h>
#include <AzCore/AzCoreModule.h>
#include <AzCore/base.h>
#include <AzCore/Casting/lossy_cast.h>
#include <AzCore/Casting/numeric_cast_internal.h>
#include <AzCore/Casting/numeric_cast.h>
#include <AzCore/Component/Component.h>
#include <AzCore/Component/ComponentApplication.h>
#include <AzCore/Component/ComponentApplicationBus.h>
#include <AzCore/Component/ComponentApplicationLifecycle.h>
#include <AzCore/Component/ComponentBus.h>
#include <AzCore/Component/ComponentExport.h>
#include <AzCore/Component/Entity.h>
#include <AzCore/Component/EntityActiveSystemBus.h>
#include <AzCore/Component/EntityActiveSystemComponent.h>
#include <AzCore/Component/EntityBus.h>
#include <AzCore/Component/EntityId.h>
#include <AzCore/Component/EntityIdSerializer.h>
#include <AzCore/Component/EntitySerializer.h>
#include <AzCore/Component/EntityUtils.h>
#include <AzCore/Component/NamedEntityId.h>
#include <AzCore/Component/NonUniformScaleBus.h>
#include <AzCore/Component/TickBus.h>
#include <AzCore/Component/TransformBus.h>
#include <AzCore/Compression/Compression.h>
#include <AzCore/Compression/zstd_compression.h>
#include <AzCore/Console/Console.h>
#include <AzCore/Console/ConsoleDataWrapper.h>
#include <AzCore/Console/ConsoleFunctor.h>
#include <AzCore/Console/ConsoleTypeHelpers.h>
#include <AzCore/Console/IConsole.h>
#include <AzCore/Console/IConsoleTypes.h>
#include <AzCore/Console/ILogger.h>
#include <AzCore/Console/LoggerSystemComponent.h>
#include <AzCore/Date/DateFormat.h>
#include <AzCore/Debug/Budget.h>
#include <AzCore/Debug/BudgetTracker.h>
#include <AzCore/Debug/MemoryProfiler.h>
#include <AzCore/Debug/PerformanceCollector.h>
#include <AzCore/Debug/Profiler.h>
#include <AzCore/Debug/ProfilerBus.h>
#include <AzCore/Debug/ProfilerReflection.h>
#include <AzCore/Debug/StackTracer.h>
#include <AzCore/Debug/Timer.h>
#include <AzCore/Debug/Trace.h>
#include <AzCore/Debug/TraceMessageBus.h>
#include <AzCore/Debug/TraceReflection.h>
#include <AzCore/Dependency/Dependency.h>
#include <AzCore/Dependency/Version.h>
#include <AzCore/Docs.h>
#include <AzCore/DOM/Backends/JSON/JsonBackend.h>
#include <AzCore/DOM/Backends/JSON/JsonSerializationUtils.h>
#include <AzCore/DOM/DomBackend.h>
#include <AzCore/DOM/DomComparison.h>
#include <AzCore/DOM/DomPatch.h>
#include <AzCore/DOM/DomPath.h>
#include <AzCore/DOM/DomPrefixTree.h>
#include <AzCore/DOM/DomUtils.h>
#include <AzCore/DOM/DomValue.h>
#include <AzCore/DOM/DomValueWriter.h>
#include <AzCore/DOM/DomVisitor.h>
#include <AzCore/EBus/BusImpl.h>
#include <AzCore/EBus/EBus.h>
#include <AzCore/EBus/EBusSharedDispatchTraits.h>
#include <AzCore/EBus/Environment.h>
#include <AzCore/EBus/Event.h>
#include <AzCore/EBus/EventSchedulerSystemComponent.h>
#include <AzCore/EBus/IEventScheduler.h>
#include <AzCore/EBus/OrderedEvent.h>
#include <AzCore/EBus/Policies.h>
#include <AzCore/EBus/Results.h>
#include <AzCore/EBus/ScheduledEvent.h>
#include <AzCore/EBus/ScheduledEventHandle.h>
#include <AzCore/Instance/InstancePool.h>
#include <AzCore/Interface/Interface.h>
#include <AzCore/IO/AnsiTerminalUtils.h>
#include <AzCore/IO/ByteContainerStream.h>
#include <AzCore/IO/CompressionBus.h>
#include <AzCore/IO/Compressor.h>
#include <AzCore/IO/CompressorStream.h>
#include <AzCore/IO/CompressorZLib.h>
#include <AzCore/IO/CompressorZStd.h>
#include <AzCore/IO/FileIO.h>
#include <AzCore/IO/FileReader.h>
#include <AzCore/IO/GenericStreams.h>
#include <AzCore/IO/IOUtils.h>
#include <AzCore/IO/IStreamer.h>
#include <AzCore/IO/IStreamerProfiler.h>
#include <AzCore/IO/IStreamerTypes.h>
#include <AzCore/IO/OpenMode.h>
#include <AzCore/IO/Path/Path_fwd.h>
#include <AzCore/IO/Path/Path.h>
#include <AzCore/IO/Path/PathReflect.h>
#include <AzCore/IO/Streamer/BlockCache.h>
#include <AzCore/IO/Streamer/DedicatedCache.h>
#include <AzCore/IO/Streamer/FileRange.h>
#include <AzCore/IO/Streamer/FileRequest.h>
#include <AzCore/IO/Streamer/FullFileDecompressor.h>
#include <AzCore/IO/Streamer/ReadSplitter.h>
#include <AzCore/IO/Streamer/RecentlyUsedIndex.h>
#include <AzCore/IO/Streamer/RequestPath.h>
#include <AzCore/IO/Streamer/Scheduler.h>
#include <AzCore/IO/Streamer/Statistics.h>
#include <AzCore/IO/Streamer/StorageDrive.h>
#include <AzCore/IO/Streamer/Streamer.h>
#include <AzCore/IO/Streamer/StreamerComponent.h>
#include <AzCore/IO/Streamer/StreamerConfiguration.h>
#include <AzCore/IO/Streamer/StreamerContext.h>
#include <AzCore/IO/Streamer/StreamStackEntry.h>
#include <AzCore/IO/SystemFile.h>
#include <AzCore/IO/TextStreamWriters.h>
#include <AzCore/IPC/SharedMemory.h>
#include <AzCore/Jobs/Algorithms.h>
#include <AzCore/Jobs/Job.h>
#include <AzCore/Jobs/JobCancelGroup.h>
#include <AzCore/Jobs/JobCompletion.h>
#include <AzCore/Jobs/JobCompletionSpin.h>
#include <AzCore/Jobs/JobContext.h>
#include <AzCore/Jobs/JobEmpty.h>
#include <AzCore/Jobs/JobFunction.h>
#include <AzCore/Jobs/JobManager.h>
#include <AzCore/Jobs/JobManagerBus.h>
#include <AzCore/Jobs/JobManagerComponent.h>
#include <AzCore/Jobs/JobManagerDesc.h>
#include <AzCore/Jobs/MultipleDependentJob.h>
#include <AzCore/Jobs/task_group.h>
#include <AzCore/JSON/allocators.h>
#include <AzCore/JSON/cursorstreamwrapper.h>
#include <AzCore/JSON/document.h>
#include <AzCore/JSON/encodedstream.h>
#include <AzCore/JSON/encodings.h>
#include <AzCore/JSON/error/en.h>
#include <AzCore/JSON/error/error.h>
#include <AzCore/JSON/filereadstream.h>
#include <AzCore/JSON/filewritestream.h>
#include <AzCore/JSON/fwd.h>
#include <AzCore/JSON/istreamwrapper.h>
#include <AzCore/JSON/memorybuffer.h>
#include <AzCore/JSON/memorystream.h>
#include <AzCore/JSON/ostreamwrapper.h>
#include <AzCore/JSON/pointer.h>
#include <AzCore/JSON/prettywriter.h>
#include <AzCore/JSON/rapidjson.h>
#include <AzCore/JSON/RapidJsonAllocator.h>
#include <AzCore/JSON/RapidjsonAllocatorAdapter.h>
#include <AzCore/JSON/reader.h>
#include <AzCore/JSON/schema.h>
#include <AzCore/JSON/stream.h>
#include <AzCore/JSON/stringbuffer.h>
#include <AzCore/JSON/writer.h>
#include <AzCore/Math/Aabb.h>
#include <AzCore/Math/Capsule.h>
#include <AzCore/Math/Color.h>
#include <AzCore/Math/ColorSerializer.h>
#include <AzCore/Math/Crc.h>
#include <AzCore/Math/CrcInternal.h>
#include <AzCore/Math/DocsMath.h>
#include <AzCore/Math/Frustum.h>
#include <AzCore/Math/Geometry2DUtils.h>
#include <AzCore/Math/Geometry3DUtils.h>
#include <AzCore/Math/Guid.h>
#include <AzCore/Math/Hemisphere.h>
#include <AzCore/Math/InterpolationSample.h>
#include <AzCore/Math/IntersectPoint.h>
#include <AzCore/Math/IntersectSegment.h>
#include <AzCore/Math/LineSegment.h>
#include <AzCore/Math/MathIntrinsics.h>
#include <AzCore/Math/MathMatrixSerializer.h>
#include <AzCore/Math/MathReflection.h>
#include <AzCore/Math/MathScriptHelpers.h>
#include <AzCore/Math/MathStringConversions.h>
#include <AzCore/Math/MathUtils.h>
#include <AzCore/Math/MathVectorSerializer.h>
#include <AzCore/Math/Matrix3x3.h>
#include <AzCore/Math/Matrix3x4.h>
#include <AzCore/Math/Matrix4x4.h>
#include <AzCore/Math/MatrixMxN.h>
#include <AzCore/Math/MatrixUtils.h>
#include <AzCore/Math/Obb.h>
#include <AzCore/Math/PackedVector2.h>
#include <AzCore/Math/PackedVector3.h>
#include <AzCore/Math/PackedVector4.h>
#include <AzCore/Math/Plane.h>
#include <AzCore/Math/PolygonPrism.h>
#include <AzCore/Math/Quaternion.h>
#include <AzCore/Math/Random.h>
#include <AzCore/Math/Ray.h>
#include <AzCore/Math/Sfmt.h>
#include <AzCore/Math/Sha1.h>
#include <AzCore/Math/ShapeIntersection.h>
#include <AzCore/Math/SimdMath.h>
#include <AzCore/Math/SimdMathVec1.h>
#include <AzCore/Math/SimdMathVec2.h>
#include <AzCore/Math/SimdMathVec3.h>
#include <AzCore/Math/SimdMathVec4.h>
#include <AzCore/Math/Sphere.h>
#include <AzCore/Math/Spline.h>
#include <AzCore/Math/Transform.h>
#include <AzCore/Math/TransformSerializer.h>
#include <AzCore/Math/Uuid.h>
#include <AzCore/Math/UuidSerializer.h>
#include <AzCore/Math/Vector2.h>
#include <AzCore/Math/Vector3.h>
#include <AzCore/Math/Vector4.h>
#include <AzCore/Math/VectorConversions.h>
#include <AzCore/Math/VectorN.h>
#include <AzCore/Math/VertexContainer.h>
#include <AzCore/Math/VertexContainerInterface.h>
#include <AzCore/Memory/AllocationRecords.h>
#include <AzCore/Memory/AllocatorBase.h>
#include <AzCore/Memory/AllocatorInstance.h>
#include <AzCore/Memory/AllocatorManager.h>
#include <AzCore/Memory/AllocatorTrackingRecorder.h>
#include <AzCore/Memory/AllocatorWrapper.h>
#include <AzCore/Memory/ChildAllocatorSchema.h>
#include <AzCore/Memory/Config.h>
#include <AzCore/Memory/HphaAllocator.h>
#include <AzCore/Memory/IAllocator.h>
#include <AzCore/Memory/Memory_fwd.h>
#include <AzCore/Memory/Memory.h>
#include <AzCore/Memory/OSAllocator.h>
#include <AzCore/Memory/PoolAllocator.h>
#include <AzCore/Memory/SimpleSchemaAllocator.h>
#include <AzCore/Memory/SystemAllocator.h>
#include <AzCore/Metrics/EventLoggerFactoryImpl.h>
#include <AzCore/Metrics/EventLoggerReflectUtils.h>
#include <AzCore/Metrics/EventLoggerUtils.h>
#include <AzCore/Metrics/IEventLogger.h>
#include <AzCore/Metrics/IEventLoggerFactory.h>
#include <AzCore/Metrics/JsonTraceEventLogger.h>
#include <AzCore/Module/DynamicModuleHandle.h>
#include <AzCore/Module/Module.h>
#include <AzCore/Module/ModuleManager.h>
#include <AzCore/Module/ModuleManagerBus.h>
#include <AzCore/Name/Name.h>
#include <AzCore/Name/NameDictionary.h>
#include <AzCore/Name/NameJsonSerializer.h>
#include <AzCore/Name/NameSerializer.h>
#include <AzCore/NativeUI/NativeUIRequests.h>
#include <AzCore/NativeUI/NativeUISystemComponent.h>
#include <AzCore/Outcome/Outcome.h>
#include <AzCore/Platform.h>
#include <AzCore/PlatformDef.h>
#include <AzCore/PlatformId/PlatformDefaults.h>
#include <AzCore/PlatformId/PlatformId.h>
// Note: AzCore/PlatformIncl.h excluded - includes Windows.h which defines macros
// (CompareString, SendMessage, etc.) that conflict with O3DE function names.
// Include PlatformIncl.h explicitly in source files that need Win32 APIs.
#include <AzCore/Preprocessor/Enum.h>
#include <AzCore/Preprocessor/EnumReflectUtils.h>
#include <AzCore/Preprocessor/Sequences.h>
#include <AzCore/Process/ProcessInfo.h>
#include <AzCore/RTTI/AttributeReader.h>
#include <AzCore/RTTI/BehaviorContext.h>
#include <AzCore/RTTI/BehaviorContextUtilities.h>
#include <AzCore/RTTI/BehaviorInterfaceProxy.h>
#include <AzCore/RTTI/BehaviorObjectSignals.h>
#include <AzCore/RTTI/ChronoReflection.h>
#include <AzCore/RTTI/ReflectContext.h>
#include <AzCore/RTTI/ReflectionManager.h>
#include <AzCore/RTTI/RTTI.h>
#include <AzCore/RTTI/RTTIMacros.h>
#include <AzCore/RTTI/TemplateInfo.h>
#include <AzCore/RTTI/TypeInfo.h>
#include <AzCore/RTTI/TypeInfoSimple.h>
#include <AzCore/RTTI/TypeSafeIntegral.h>
#include <AzCore/Script/lua/lua.h>
#include <AzCore/Script/ScriptAsset.h>
#include <AzCore/Script/ScriptContext.h>
#include <AzCore/Script/ScriptContextAttributes.h>
#include <AzCore/Script/ScriptContextDebug.h>
#include <AzCore/Script/ScriptDebug.h>
#include <AzCore/Script/ScriptProperty.h>
#include <AzCore/Script/ScriptPropertySerializer.h>
#include <AzCore/Script/ScriptPropertyTable.h>
#include <AzCore/Script/ScriptPropertyWatcherBus.h>
#include <AzCore/Script/ScriptSystemBus.h>
#include <AzCore/Script/ScriptSystemComponent.h>
#include <AzCore/Script/ScriptTimePoint.h>
#include <AzCore/ScriptCanvas/ScriptCanvasAttributes.h>
#include <AzCore/ScriptCanvas/ScriptCanvasOnDemandNames.h>
#include <AzCore/Serialization/DataOverlay.h>
#include <AzCore/Serialization/DataOverlayInstanceMsgs.h>
#include <AzCore/Serialization/DataOverlayProviderMsgs.h>
#include <AzCore/Serialization/DataPatch.h>
#include <AzCore/Serialization/DataPatchBus.h>
#include <AzCore/Serialization/DataPatchUpgradeManager.h>
#include <AzCore/Serialization/DynamicSerializableField.h>
#include <AzCore/Serialization/EditContext.h>
#include <AzCore/Serialization/EnumConstantJsonSerializer.h>
#include <AzCore/Serialization/IdUtils.h>
#include <AzCore/Serialization/Json/AnySerializer.h>
#include <AzCore/Serialization/Json/ArraySerializer.h>
#include <AzCore/Serialization/Json/BaseJsonSerializer.h>
#include <AzCore/Serialization/Json/BasicContainerSerializer.h>
#include <AzCore/Serialization/Json/BoolSerializer.h>
#include <AzCore/Serialization/Json/ByteStreamSerializer.h>
#include <AzCore/Serialization/Json/CastingHelpers.h>
#include <AzCore/Serialization/Json/DoubleSerializer.h>
#include <AzCore/Serialization/Json/IntSerializer.h>
#include <AzCore/Serialization/Json/JsonDeserializer.h>
#include <AzCore/Serialization/Json/JsonImporter.h>
#include <AzCore/Serialization/Json/JsonMerger.h>
#include <AzCore/Serialization/Json/JsonSerialization.h>
#include <AzCore/Serialization/Json/JsonSerializationMetadata.h>
#include <AzCore/Serialization/Json/JsonSerializationResult.h>
#include <AzCore/Serialization/Json/JsonSerializationSettings.h>
#include <AzCore/Serialization/Json/JsonSerializer.h>
#include <AzCore/Serialization/Json/JsonStringConversionUtils.h>
#include <AzCore/Serialization/Json/JsonSystemComponent.h>
#include <AzCore/Serialization/Json/JsonUtils.h>
#include <AzCore/Serialization/Json/MapSerializer.h>
#include <AzCore/Serialization/Json/PathSerializer.h>
#include <AzCore/Serialization/Json/PointerJsonSerializer.h>
#include <AzCore/Serialization/Json/RegistrationContext.h>
#include <AzCore/Serialization/Json/SmartPointerSerializer.h>
#include <AzCore/Serialization/Json/StackedString.h>
#include <AzCore/Serialization/Json/StringSerializer.h>
#include <AzCore/Serialization/Json/TupleSerializer.h>
#include <AzCore/Serialization/Json/UnorderedSetSerializer.h>
#include <AzCore/Serialization/Json/UnsupportedTypesSerializer.h>
#include <AzCore/Serialization/Locale.h>
#include <AzCore/Serialization/ObjectStream.h>
#include <AzCore/Serialization/PointerObject.h>
#include <AzCore/Serialization/SerializeContext_fwd.h>
#include <AzCore/Serialization/SerializeContext.h>
#include <AzCore/Serialization/Utils.h>
#include <AzCore/Settings/CommandLine.h>
#include <AzCore/Settings/CommandLineParser.h>
#include <AzCore/Settings/ConfigParser.h>
#include <AzCore/Settings/ConfigurableStack.h>
#include <AzCore/Settings/SettingsRegistry.h>
#include <AzCore/Settings/SettingsRegistryConsoleUtils.h>
#include <AzCore/Settings/SettingsRegistryImpl.h>
#include <AzCore/Settings/SettingsRegistryMergeUtils.h>
#include <AzCore/Settings/SettingsRegistryOriginTracker.h>
#include <AzCore/Settings/SettingsRegistryScriptUtils.h>
#include <AzCore/Settings/SettingsRegistryVisitorUtils.h>
#include <AzCore/Settings/TextParser.h>
#include <AzCore/Slice/SliceAsset.h>
#include <AzCore/Slice/SliceAssetHandler.h>
#include <AzCore/Slice/SliceBus.h>
#include <AzCore/Slice/SliceComponent.h>
#include <AzCore/Slice/SliceMetadataInfoBus.h>
#include <AzCore/Slice/SliceMetadataInfoComponent.h>
#include <AzCore/Slice/SliceSystemComponent.h>
// Note: AzCore/Socket/AzSocket.h excluded - includes PlatformIncl.h (Windows.h)
#include <AzCore/Socket/AzSocket_fwd.h>
#include <AzCore/State/HSM.h>
#include <AzCore/Statistics/NamedRunningStatistic.h>
#include <AzCore/Statistics/RunningStatistic.h>
#include <AzCore/Statistics/StatisticalProfiler.h>
#include <AzCore/Statistics/StatisticalProfilerProxy.h>
#include <AzCore/Statistics/StatisticalProfilerProxySystemComponent.h>
#include <AzCore/Statistics/StatisticsManager.h>
#include <AzCore/StringFunc/StringFunc.h>
#include <AzCore/Task/TaskDescriptor.h>
#include <AzCore/Task/TaskExecutor.h>
#include <AzCore/Task/TaskGraph.h>
#include <AzCore/Task/TaskGraphSystemComponent.h>
#include <AzCore/Threading/ThreadSafeDeque.h>
#include <AzCore/Threading/ThreadSafeObject.h>
#include <AzCore/Threading/ThreadUtils.h>
#include <AzCore/Time/ITime.h>
#include <AzCore/Time/TimeSystem.h>
#include <AzCore/UserSettings/UserSettings.h>
#include <AzCore/UserSettings/UserSettingsComponent.h>
#include <AzCore/UserSettings/UserSettingsProvider.h>
#include <AzCore/Utils/TypeHash.h>
#include <AzCore/Utils/Utils.h>
#include <AzCore/variadic.h>
// Note: AzCore/XML/rapidxml_iterators.h excluded - has compilation errors in upstream RapidXML (++this)
// Note: AzCore/XML/rapidxml_print.h, rapidxml_utils.h excluded - depend on rapidxml_iterators.h order
#include <AzCore/XML/rapidxml.h>
#include <AzCore/std/algorithm.h>
#include <AzCore/std/allocator_ref.h>
#include <AzCore/std/allocator_stack.h>
#include <AzCore/std/allocator_stateless.h>
#include <AzCore/std/allocator_static.h>
#include <AzCore/std/allocator_traits.h>
#include <AzCore/std/allocator.h>
#include <AzCore/std/any.h>
#include <AzCore/std/base.h>
#include <AzCore/std/bind/bind.h>
#include <AzCore/std/bind/mem_fn.h>
#include <AzCore/std/chrono/chrono.h>
#include <AzCore/std/concepts/concepts_assignable.h>
#include <AzCore/std/concepts/concepts_constructible.h>
#include <AzCore/std/concepts/concepts_copyable.h>
#include <AzCore/std/concepts/concepts_movable.h>
#include <AzCore/std/concepts/concepts.h>
#include <AzCore/std/config.h>
#include <AzCore/std/containers/array_fwd.h>
#include <AzCore/std/containers/array.h>
#include <AzCore/std/containers/bitset.h>
#include <AzCore/std/containers/compressed_pair.h>
#include <AzCore/std/containers/containers_concepts.h>
#include <AzCore/std/containers/deque.h>
#include <AzCore/std/containers/fixed_forward_list.h>
#include <AzCore/std/containers/fixed_list.h>
#include <AzCore/std/containers/fixed_unordered_map.h>
#include <AzCore/std/containers/fixed_unordered_set.h>
#include <AzCore/std/containers/fixed_vector.h>
#include <AzCore/std/containers/forward_list.h>
#include <AzCore/std/containers/intrusive_list.h>
#include <AzCore/std/containers/intrusive_set.h>
#include <AzCore/std/containers/intrusive_slist.h>
#include <AzCore/std/containers/list.h>
#include <AzCore/std/containers/map.h>
#include <AzCore/std/containers/node_handle.h>
#include <AzCore/std/containers/queue.h>
#include <AzCore/std/containers/rbtree.h>
#include <AzCore/std/containers/ring_buffer.h>
#include <AzCore/std/containers/set.h>
#include <AzCore/std/containers/span_fwd.h>
#include <AzCore/std/containers/span.h>
#include <AzCore/std/containers/stack.h>
#include <AzCore/std/containers/unordered_map.h>
#include <AzCore/std/containers/unordered_set.h>
#include <AzCore/std/containers/variant_impl.h>
#include <AzCore/std/containers/variant.h>
#include <AzCore/std/containers/vector.h>
#include <AzCore/std/createdestroy.h>
#include <AzCore/std/delegate/delegate_bind.h>
#include <AzCore/std/delegate/delegate_fwd.h>
#include <AzCore/std/delegate/delegate.h>
#include <AzCore/std/docs.h>
#include <AzCore/std/exceptions.h>
#include <AzCore/std/function/function_base.h>
#include <AzCore/std/function/function_fwd.h>
#include <AzCore/std/function/function_template.h>
#include <AzCore/std/function/identity.h>
#include <AzCore/std/function/invoke.h>
#include <AzCore/std/functional_basic.h>
#include <AzCore/std/functional.h>
#include <AzCore/std/hash_table.h>
#include <AzCore/std/hash.h>
#include <AzCore/std/iterator.h>
#include <AzCore/std/iterator/common_iterator.h>
#include <AzCore/std/iterator/const_iterator.h>
#include <AzCore/std/iterator/counted_iterator.h>
#include <AzCore/std/iterator/iterator_primitives.h>
#include <AzCore/std/iterator/move_iterator.h>
#include <AzCore/std/iterator/move_sentinel.h>
#include <AzCore/std/iterator/unreachable_sentinel.h>
#include <AzCore/std/limits.h>
#include <AzCore/std/math.h>
#include <AzCore/std/metaprogramming/ratio.h>
#include <AzCore/std/numeric.h>
#include <AzCore/std/optional.h>
#include <AzCore/std/parallel/allocator_concurrent_static.h>
#include <AzCore/std/parallel/atomic.h>
#include <AzCore/std/parallel/binary_semaphore.h>
#include <AzCore/std/parallel/combinable.h>
#include <AzCore/std/parallel/condition_variable.h>
#include <AzCore/std/parallel/conditional_variable.h>
#include <AzCore/std/parallel/config.h>
#include <AzCore/std/parallel/containers/concurrent_fixed_unordered_map.h>
#include <AzCore/std/parallel/containers/concurrent_fixed_unordered_set.h>
#include <AzCore/std/parallel/containers/concurrent_unordered_map.h>
#include <AzCore/std/parallel/containers/concurrent_unordered_set.h>
#include <AzCore/std/parallel/containers/concurrent_vector.h>
#include <AzCore/std/parallel/containers/lock_free_intrusive_stack.h>
#include <AzCore/std/parallel/containers/lock_free_intrusive_stamped_stack.h>
#include <AzCore/std/parallel/containers/lock_free_queue.h>
#include <AzCore/std/parallel/containers/lock_free_stack.h>
#include <AzCore/std/parallel/containers/lock_free_stamped_queue.h>
#include <AzCore/std/parallel/containers/lock_free_stamped_stack.h>
#include <AzCore/std/parallel/exponential_backoff.h>
#include <AzCore/std/parallel/lock.h>
#include <AzCore/std/parallel/mutex.h>
#include <AzCore/std/parallel/scoped_lock.h>
#include <AzCore/std/parallel/semaphore.h>
#include <AzCore/std/parallel/shared_mutex.h>
#include <AzCore/std/parallel/spin_mutex.h>
#include <AzCore/std/parallel/thread.h>
#include <AzCore/std/parallel/threadbus.h>
#include <AzCore/std/ranges/all_view.h>
#include <AzCore/std/ranges/as_const_view.h>
#include <AzCore/std/ranges/as_rvalue_view.h>
#include <AzCore/std/ranges/common_view.h>
#include <AzCore/std/ranges/counted_view.h>
#include <AzCore/std/ranges/elements_view.h>
#include <AzCore/std/ranges/empty_view.h>
#include <AzCore/std/ranges/filter_view.h>
#include <AzCore/std/ranges/iota_internal.h>
#include <AzCore/std/ranges/iota_view.h>
#include <AzCore/std/ranges/iter_move.h>
#include <AzCore/std/ranges/iter_swap.h>
#include <AzCore/std/ranges/join_view.h>
#include <AzCore/std/ranges/join_with_view.h>
#include <AzCore/std/ranges/owning_view.h>
#include <AzCore/std/ranges/ranges_adaptor.h>
#include <AzCore/std/ranges/ranges_algorithm.h>
#include <AzCore/std/ranges/ranges_functional.h>
#include <AzCore/std/ranges/ranges_to.h>
#include <AzCore/std/ranges/ranges.h>
#include <AzCore/std/ranges/ref_view.h>
#include <AzCore/std/ranges/repeat_view.h>
#include <AzCore/std/ranges/reverse_view.h>
#include <AzCore/std/ranges/single_view.h>
#include <AzCore/std/ranges/split_view.h>
#include <AzCore/std/ranges/subrange_fwd.h>
#include <AzCore/std/ranges/subrange.h>
#include <AzCore/std/ranges/swap.h>
#include <AzCore/std/ranges/transform_view.h>
#include <AzCore/std/ranges/zip_view.h>
#include <AzCore/std/reference_wrapper.h>
#include <AzCore/std/smart_ptr/checked_delete.h>
#include <AzCore/std/smart_ptr/enable_shared_from_this.h>
#include <AzCore/std/smart_ptr/enable_shared_from_this2.h>
#include <AzCore/std/smart_ptr/intrusive_base.h>
#include <AzCore/std/smart_ptr/intrusive_ptr.h>
#include <AzCore/std/smart_ptr/intrusive_refcount.h>
#include <AzCore/std/smart_ptr/make_shared.h>
#include <AzCore/std/smart_ptr/scoped_array.h>
#include <AzCore/std/smart_ptr/scoped_ptr.h>
#include <AzCore/std/smart_ptr/shared_array.h>
#include <AzCore/std/smart_ptr/shared_count.h>
#include <AzCore/std/smart_ptr/shared_ptr.h>
#include <AzCore/std/smart_ptr/sp_convertible.h>
#include <AzCore/std/smart_ptr/unique_ptr.h>
#include <AzCore/std/smart_ptr/weak_ptr.h>
#include <AzCore/std/sort.h>
#include <AzCore/std/string/alphanum.h>
#include <AzCore/std/string/conversions.h>
#include <AzCore/std/string/fixed_string.h>
#include <AzCore/std/string/memorytoascii.h>
#include <AzCore/std/string/osstring.h>
// Note: AzCore/std/string/regex.h excluded - extern template conflicts with explicit specializations in regex.cpp
#include <AzCore/std/string/string_view.h>
#include <AzCore/std/string/string.h>
#include <AzCore/std/string/tokenize.h>
#include <AzCore/std/string/utf8/core.h>
#include <AzCore/std/string/utf8/unchecked.h>
#include <AzCore/std/string/wildcard.h>
#include <AzCore/std/time.h>
#include <AzCore/std/tuple.h>
#include <AzCore/std/typetraits/add_const.h>
#include <AzCore/std/typetraits/add_cv.h>
#include <AzCore/std/typetraits/add_pointer.h>
#include <AzCore/std/typetraits/add_reference.h>
#include <AzCore/std/typetraits/add_volatile.h>
#include <AzCore/std/typetraits/aligned_storage.h>
#include <AzCore/std/typetraits/alignment_of.h>
#include <AzCore/std/typetraits/common_reference.h>
#include <AzCore/std/typetraits/common_type.h>
#include <AzCore/std/typetraits/conditional.h>
#include <AzCore/std/typetraits/config.h>
#include <AzCore/std/typetraits/conjunction.h>
#include <AzCore/std/typetraits/decay.h>
#include <AzCore/std/typetraits/disjunction.h>
#include <AzCore/std/typetraits/extent.h>
#include <AzCore/std/typetraits/function_traits.h>
#include <AzCore/std/typetraits/has_member_function.h>
#include <AzCore/std/typetraits/has_virtual_destructor.h>
#include <AzCore/std/typetraits/integral_constant.h>
#include <AzCore/std/typetraits/intrinsics.h>
#include <AzCore/std/typetraits/invoke_traits.h>
#include <AzCore/std/typetraits/is_abstract.h>
#include <AzCore/std/typetraits/is_arithmetic.h>
#include <AzCore/std/typetraits/is_array.h>
#include <AzCore/std/typetraits/is_assignable.h>
#include <AzCore/std/typetraits/is_base_of.h>
#include <AzCore/std/typetraits/is_class.h>
#include <AzCore/std/typetraits/is_compound.h>
#include <AzCore/std/typetraits/is_const.h>
#include <AzCore/std/typetraits/is_constructible.h>
#include <AzCore/std/typetraits/is_convertible.h>
#include <AzCore/std/typetraits/is_destructible.h>
#include <AzCore/std/typetraits/is_empty.h>
#include <AzCore/std/typetraits/is_enum.h>
#include <AzCore/std/typetraits/is_floating_point.h>
#include <AzCore/std/typetraits/is_function.h>
#include <AzCore/std/typetraits/is_fundamental.h>
#include <AzCore/std/typetraits/is_integral.h>
#include <AzCore/std/typetraits/is_lvalue_reference.h>
#include <AzCore/std/typetraits/is_member_function_pointer.h>
#include <AzCore/std/typetraits/is_member_object_pointer.h>
#include <AzCore/std/typetraits/is_member_pointer.h>
#include <AzCore/std/typetraits/is_object.h>
#include <AzCore/std/typetraits/is_pointer.h>
#include <AzCore/std/typetraits/is_polymorphic.h>
#include <AzCore/std/typetraits/is_reference.h>
#include <AzCore/std/typetraits/is_rvalue_reference.h>
#include <AzCore/std/typetraits/is_same.h>
#include <AzCore/std/typetraits/is_scalar.h>
#include <AzCore/std/typetraits/is_signed.h>
#include <AzCore/std/typetraits/is_swappable.h>
#include <AzCore/std/typetraits/is_trivial.h>
#include <AzCore/std/typetraits/is_trivially_copyable.h>
#include <AzCore/std/typetraits/is_union.h>
#include <AzCore/std/typetraits/is_unsigned.h>
#include <AzCore/std/typetraits/is_void.h>
#include <AzCore/std/typetraits/is_volatile.h>
#include <AzCore/std/typetraits/negation.h>
#include <AzCore/std/typetraits/rank.h>
#include <AzCore/std/typetraits/remove_all_extents.h>
#include <AzCore/std/typetraits/remove_const.h>
#include <AzCore/std/typetraits/remove_cv.h>
#include <AzCore/std/typetraits/remove_cvref.h>
#include <AzCore/std/typetraits/remove_extent.h>
#include <AzCore/std/typetraits/remove_pointer.h>
#include <AzCore/std/typetraits/remove_reference.h>
#include <AzCore/std/typetraits/remove_volatile.h>
#include <AzCore/std/typetraits/static_storage.h>
#include <AzCore/std/typetraits/type_id.h>
#include <AzCore/std/typetraits/type_identity.h>
#include <AzCore/std/typetraits/typetraits.h>
#include <AzCore/std/typetraits/underlying_type.h>
#include <AzCore/std/typetraits/void_t.h>
#include <AzCore/std/utility/as_const.h>
#include <AzCore/std/utility/charconv.h>
#include <AzCore/std/utility/declval.h>
#include <AzCore/std/utility/expected_internal.h>
#include <AzCore/std/utility/expected.h>
#include <AzCore/std/utility/move.h>
#include <AzCore/std/utility/pair_fwd.h>
#include <AzCore/std/utility/pair.h>
#include <AzCore/std/utility/to_underlying.h>
#include <AzCore/std/utility/tuple_concepts.h>
#include <AzCore/std/utility/tuple_fwd.h>
#include <AzCore/std/utils.h>
