name: Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  inspect-code:
    name: Inspect Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa-dev libxcb-xinerama0 libxcb-xinput0 libfontconfig1-dev libxcb-xkb-dev libxkbcommon-x11-dev libxkbcommon-dev libxcb-xfixes0-dev libxcb-xinput-dev libxcb-randr0-dev libxcb-keysyms1-dev libpcre2-16-0 zlib1g-dev mesa-common-dev libunwind-dev libzstd-dev pkg-config

      - name: Setup CMake
        uses: lukka/get-cmake@f176ccd3f28bda569c43aae4894f06b2435a3375 # v4.2.3
        with:
          useCloudCache: true
          useLocalCache: true
          cmakeVersion: "4.2.3"
          ninjaVersion: "1.13.2"

      - name: Configure
        env:
          CMAKE_BUILD_TYPE: Release
        run: cmake -B Build -G "Visual Studio 18 2026"

      - name: Annotate
        uses: JetBrains/ReSharper-InspectCode@v0.11
        with:
          solution: Build/O3DE.slnx

    permissions:
      security-events: write
