#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

name: Mac Build

# These jobs are to be triggered by ar.yml

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image:
        type: string
        default: macos-15-intel
      config:
        type: string
        required: true
      type:
        type: string
        required: true
      last_artifact:
        type: boolean
        required: false
      cmake_version:
        type: string
        required: false

run-name: Mac - ${{ inputs.type }}

# Note: All 3P Github Actions use the commit hash for security reasons
# Avoid using the tag version, which is vulnerable to supply chain attacks

jobs:
  Build:
    runs-on: ${{ inputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false

      - name: LFS Pull
        uses: ./.github/actions/lfs-pull
        with:
          include: ${{ inputs.type == 'profile' && '*.ico,*.bmp' || '' }}

      - name: Setup 3p, user, and build folders
        run: |
          mkdir -p .o3de/python build 3rdParty \
            Cache/CCache Cache/PythonPackages Cache/3rdPartyPackages Cache/AutomatedTestingCache
          ln -sf "$(pwd)/.o3de" ~/.o3de
          ln -sfn "$(pwd)/Cache/PythonPackages" .o3de/python/downloaded_packages
          ln -sfn "$(pwd)/Cache/3rdPartyPackages" 3rdParty/downloaded_packages
          ln -sfn "$(pwd)/Cache/AutomatedTestingCache" AutomatedTesting/Cache

      - name: Setup Cache Artifact
        uses: ./.github/actions/cache-artifact
        with:
          name: cache-mac-${{ inputs.config }}
          search-previous: ${{ inputs.last_artifact }}
          save: ${{ !contains(inputs.type, 'test') }}

      - name: Provision
        uses: ./.github/actions/provision
        with:
          ccache: "4.12.3"
          cmake: ${{ inputs.cmake_version }}

      - name: Configure ccache
        run: |
          ccache --set-config cache_dir=${{ github.workspace }}/Cache/CCache
          ccache --set-config hash_dir=false
          ccache --set-config max_size=10G

      - name: Configure environment
        continue-on-error: true
        run: |
          echo "Installing dependencies"
          brew install --quiet xcbeautify
          echo "Getting python..."
          ./python/get_python.sh
          echo "Installing additional python dependencies..."
          ./python/pip.sh install tempfile2 PyGithub
          df -h

      - name: Build (${{ inputs.type }})
        # Builds with presets in ../scripts/build/Platform/Mac/build_config.json
        timeout-minutes: 330
        env:
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
          LY_3RDPARTY_PATH: ${{ github.workspace }}/3rdParty
          LY_PACKAGE_SERVER_URLS: https://d1gg6ket0m44ly.cloudfront.net;https://d3t6xeg4fgfoum.cloudfront.net
        run: python/python.sh -u scripts/build/ci_build.py --platform Mac --type ${{ inputs.type }}


