name: Build

on:
  push:

jobs:
  build:
    name: Build ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Linux
            image: ubuntu-24.04
          # - platform: Mac
          #   image: macos-26
          # - platform: Windows
          #   image: windows-2022

    runs-on: ${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Git lfs pull
        run: |
          git lfs install
          git lfs pull

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.o3de
          key: o3de-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          restore-keys: |
            o3de-${{ runner.os }}-${{ runner.arch }}-

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
          
      - name: Setup cmake
        uses: lukka/get-cmake@v4.2.1
        with:
          cmakeVersion: "4.2.1"
          ninjaVersion: "1.13.2"
          useCloudCache: true
          useLocalCache: true

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          
      - name: Install dependencies
        if: matrix.platform == 'Linux'
        continue-on-error: true
        run: |
          pushd scripts/build/build_node/Platform/Linux
          sudo ./install-ubuntu.sh
          popd

      - name: Build
        timeout-minutes: 330
        env:
          LY_PACKAGE_SERVER_URLS: https://d1gg6ket0m44ly.cloudfront.net;https://d3t6xeg4fgfoum.cloudfront.net
          CMAKE_C_COMPILER_LAUNCHER: sccache
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
          SCCACHE_GHA_ENABLED: true
        run: python -u scripts/build/ci_build.py --platform ${{ matrix.platform}} --type profile

      - name: Save cache
        if: always() && steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/.o3de
          key: ${{ steps.cache.outputs.cache-primary-key }}
