name: Build Mac

on:
  push:

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false

    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Git lfs pull
        run: |
          git lfs install
          git lfs pull

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      # - name: Configure sccache
      #   uses: actions/github-script@v8
      #   with:
      #     script: |
      #       core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
      #       core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.o3de
            Cache
          key: ${{ runner.os }}-${{ runner.arch }}

      - name: Setup cmake
        uses: lukka/get-cmake@v4.2.1
        with:
          cmakeVersion: "4.2.1"
          ninjaVersion: "1.13.2"
          useCloudCache: true
          useLocalCache: true

      - name: Configure environment
        continue-on-error: true
        run: |
          echo "Getting python..."
          ./python/get_python.sh
          echo "Installing additional python dependencies..."
          ./python/pip.sh install tempfile2 PyGithub

      - name: Build (Profile)
        timeout-minutes: 330
        run: |
          export LY_3RDPARTY_PATH=${{ github.workspace }}/Cache/3rdParty
          export LY_PACKAGE_SERVER_URLS="https://d1gg6ket0m44ly.cloudfront.net;https://d3t6xeg4fgfoum.cloudfront.net"
          export CMAKE_C_COMPILER_LAUNCHER=sccache
          export CMAKE_CXX_COMPILER_LAUNCHER=sccache
          export SCCACHE_GHA_ENABLED=true
          python/python.sh -u scripts/build/ci_build.py --platform Mac --type profile
