name: Build

on:
  workflow_call:
    inputs:
      platform:
        type: string
        required: true
      type:
        type: string
        default: Profile
      cache:
        type: boolean
        default: true

  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        type: choice
        default: Linux
        options:
          - Android
          - iOS
          - Linux
          - Mac
          - Windows
      type:
        description: Build Type
        type: string
        default: Profile

jobs:
  build:
    name: ${{ inputs.type }}

    runs-on: |
      ${{ fromJSON('{
        "Android":"windows-2022",
        "iOS":"macos-15",
        "Linux":"ubuntu-24.04",
        "Mac":"macos-26",
        "Windows":"windows-2022"
      }')[inputs.platform] }}

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # v10
        if: runner.os == 'Linux'
        with:
          root-reserve-mb: 8000
          swap-size-mb: 200
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true

      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Git lfs pull
        run: |
          git lfs install
          git lfs pull

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v4
        if: ${{ inputs.cache }}
        with:
          path: |
            ~/.o3de/3rdParty
            ~/.o3de/Cache
            ~/.o3de/Python
          key: O3DE-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          restore-keys: |
            O3DE-${{ runner.os }}-${{ runner.arch }}-
            O3DE-${{ runner.os }}-

git      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          pip-install: -r python/requirements.txt
          cache: pip

      - name: Setup cmake
        uses: lukka/get-cmake@v4.2.1
        with:
          cmakeVersion: "4.2.1"
          ninjaVersion: "1.13.2"
          useCloudCache: true
          useLocalCache: true

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Setup platform
        continue-on-error: true
        run: scripts/build/build_node/Platform/${{ inputs.platform }}/setup.ps1

      - name: Build (${{ inputs.type }})
        timeout-minutes: 330
        env:
          CMAKE_C_COMPILER_LAUNCHER: sccache
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
          LY_PACKAGE_SERVER_URLS: https://d1gg6ket0m44ly.cloudfront.net;https://d3t6xeg4fgfoum.cloudfront.net
          NDK_VERSION: "25.1.8937393"
          SCCACHE_GHA_ENABLED: true
        run: >-
          python -u scripts/build/ci_build.py
          --platform ${{ inputs.platform }}
          --type ${{ inputs.type }}

      - name: Save cache
        if: ${{ always() && inputs.cache && steps.cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: ~/.o3de
          key: ${{ steps.cache.outputs.cache-primary-key }}
